window.KO={
// ===== SHARED NAV =====
'nav.summit':'서밋',
'nav.congress':'학술대회',
'nav.kat':'KAT',
'nav.speakers':'연사진',
'nav.business':'비즈니스',
'nav.register':'무료 등록',
'nav.reg':'등록',
'nav.regmeet':'미팅 등록',

// ===== SHARED FOOTER =====
'ft.events':'행사',
'ft.register':'등록',
'ft.more':'더보기',
'ft.speakers':'연사진',
'ft.contact':'KBIT 문의',
'ft.copy':'© 2026 K-Beauty MEETS · KBIT 주관',
'ft.tagline':'K-Beauty · Medical · Excellence · Exchange · Training · Skills<br>호치민시 + 하노이 · 2026년 10월',
'ft.reg.summit':'서밋 등록',
'ft.reg.kat':'KAT 등록',
'ft.reg.congress':'학술대회 등록',
'ft.ev.summit':'KSAPS 서밋 · 10월 3일 · 호치민시',
'ft.ev.kat':'KAT 베트남 2026 · 10월 23일 · 호치민시 (미정)',
'ft.ev.congress':'KSAPS 학술대회 · 10월 17–18일 · 하노이',

// ===== INDEX PAGE =====
'idx.supported':'후원',
'idx.organized':'주최',
'idx.khidi':'KHIDI',
'idx.mohw':'대한민국 보건복지부',
'idx.eyebrow':'호치민시 & 하노이, 베트남 · 2026년 10월',
'idx.sub':'K-Beauty · Medical · Excellence · Exchange · Training · Skills',
'idx.tagline':'한국의 우수한 의료기술이 아시아를 만나다',
'idx.btn.summit':'서밋 둘러보기 →',
'idx.btn.congress':'학술대회 등록 →',
'idx.btn.kat':'KAT 등록',
'idx.hd.summit':'KSAPS 서밋',
'idx.hd.kat':'KAT 베트남',
'idx.hd.congress':'KSAPS 학술대회',
'idx.hd.hcmc':'호치민시',
'idx.hd.hanoi':'하노이',

// What is K-Beauty MEETS
'idx.meets.eyb':'K-Beauty MEETS란?',
'idx.meets.h2':'학회 그 이상 —<br>의료 <em style="color:#5DCBA8;font-style:italic">혁신의 움직임</em>',
'idx.meets.desc':'K-Beauty MEETS는 베트남 최고의 미용의학 전문의들이 한국의 저명한 KOL과 직접 교류하는 프로그램입니다 — 라이브 수술, 기기 시연, 실습을 통해 호치민시와 하노이의 세계적 수준의 병원에서 진행됩니다.',
'idx.mc.kbeauty':'K-Beauty',
'idx.mc.kpill':'한국<br>미용의학 기준',
'idx.mc.medical':'Medical',
'idx.mc.excellence':'Excellence',
'idx.mc.epill':'15명 KOL<br>K-스탠다드 프로토콜',
'idx.mc.exchange':'Exchange',
'idx.mc.expill':'KOL<br>Q&A 패널',
'idx.mc.training':'Training',
'idx.mc.tpill':'학술대회 · CME<br>핸즈온',
'idx.mc.skills':'Skills',
'idx.mc.spill':'KAT<br>라이브 수술',

// Why K-Beauty MEETS
'idx.why.eyb':'왜 K-Beauty MEETS인가?',
'idx.why.h2':'기준이 바뀌었습니다.<br><em>준비되셨습니까?</em>',
'idx.why.lead':'한국 미용의학은 세계를 선도합니다. K-Beauty MEETS는 베트남 의사들에게 그 기준을 이끄는 전문가, 프로토콜, 기기에 직접 접근할 수 있는 기회를 제공합니다 — 교과서가 아닌 자신의 도시에서의 실습 경험을 통해.',
'idx.why1.title':'한국 KOL 직접 교류',
'idx.why1.desc':'KSAPS와 SNUBH 소속 15명의 핵심 오피니언 리더(KOL) — 한국에서 가장 존경받는 미용성형 학회입니다. 녹화된 강의가 아닙니다. 실제 외과의와 의사들이 여러분과 같은 공간에서 수술하고 실시간으로 질문에 답합니다.',
'idx.why2.title':'이론이 아닌 K-스탠다드 프로토콜',
'idx.why2.desc':'라이브 기기 시연. 라이브 수술 방송. 1:5 소그룹 핸즈온. 모든 세션은 임상 적용 중심으로 설계되었습니다 — 베트남 환자에 맞게 조정된, 클리닉에서 즉시 사용할 수 있는 프로토콜.',
'idx.why3.title':'정부 지원, 무료 참가',
'idx.why3.desc':'보건복지부 산하 한국보건산업진흥원(KHIDI) 지원. 모든 행사는 베트남 의료 전문가에게 무료입니다. 좌석 한정, 심사 기반 등록.',

// 2026 Series
'idx.ev.eyb':'2026 시리즈',
'idx.ev.h2':'두 도시. 세 개의 행사.<br>하나의 <em style="color:#5DCBA8;font-style:italic">움직임.</em>',
'idx.ev.desc':'호치민시의 집중 임상 워크숍부터 하노이의 베트남 최대 한국 미용의학 학술대회까지 — K-Beauty MEETS 2026은 두 도시, 나흘에 걸쳐 진행됩니다.',
'idx.ec.summit.badge':'Korea Meets VSAPS · 호치민시',
'idx.ec.summit.theme':'"Korean Beauty — 미용성형 및 의료기기 최신 동향"',
'idx.ec.summit.meta':'2026년 10월 3일 · 강남미용성형병원',
'idx.ec.summit.b1':'의사 100명 · 1일 · 호치민시',
'idx.ec.summit.b2':'기자회견 · 강연 · 라이브 기기 시연 · 라이브 수술',
'idx.ec.summit.b4':'K-프로토콜 수료증',
'idx.ec.summit.desc':'강남미용성형병원에서의 집중 2일 워크숍 — 베트남 최고의 민간 미용성형 시설. 1일차: 강연 및 라이브 기기 시연. 2일차: 기자회견, 라이브 수술 방송, 보톡스/필러/실리프팅 핸즈온 교육.',
'idx.ec.summit.free':'<strong>무료</strong> · 100명 한정',
'idx.ec.learn':'자세히 보기',
'idx.ec.kat.badge':'KAT · 호치민시',
'idx.ec.kat.theme':'"당신의 손. 한국의 기술."',
'idx.ec.kat.meta':'2026년 10월 23일 (미정) · 호치민시',
'idx.ec.kat.b1':'독립 행사 2일차',
'idx.ec.kat.b2':'라이브 기기 시연 · 보톡스 & 필러 라이브 · 라이브 성형수술',
'idx.ec.kat.b3':'라이브 성형수술',
'idx.ec.kat.b4':'KAT 2026 수료증 · CME 수료증',
'idx.ec.kat.desc':'K-Beauty Advanced Skills Training — 공동 주최. 순수 기술 전수: OR에서의 라이브 수술, 기기 시연, 한국 KOL 지도 아래 보톡스 및 필러 직접 실습.',
'idx.ec.kat.free':'<strong>무료</strong> · 좌석 한정',
'idx.ec.congress.badge':'Korea Meets VSAPS · 하노이',
'idx.ec.congress.theme':'"Korean Beauty — 최첨단 미용성형 및 의료 기술"',
'idx.ec.congress.meta':'2026년 10월 17–18일 · 108 중앙군사병원, 하노이',
'idx.ec.congress.b1':'약 1,000명 참가 · 2일 · 하노이',
'idx.ec.congress.b2':'학술 세션 + 3개 병행 트랙',
'idx.ec.congress.b3':'한국 기업 10개사 전시',
'idx.ec.congress.b4':'핸즈온 워크숍 + 갈라 디너',
'idx.ec.congress.desc':'베트남 최대 한·베 미용의학 학술대회. 하노이 108 중앙군사병원에서 이틀간 — 학술 세션, 병행 트랙, 10개사 전시, 라이브 수술, 핸즈온 교육, VIP 갈라 디너.',
'idx.ec.congress.free':'<strong>무료</strong> · 좌석 한정',

// KAT Timeline
'idx.kat.eyb':'KAT',
'idx.kat.h2':'한국의 교육 시리즈 —<br><em>아시아로 확장</em>',
'idx.kat.lead':'KAT — K-Beauty Advanced Skills Training — 한국 KOL이 현지 의사들에게 직접 실습 기술을 전수합니다. 매년 새로운 아시아 도시. 매 회차마다 더 깊어지는 한국 교육 미용 전문가 네트워크.',
'idx.kat.desc2':'KAT 2025는 350명의 의사를 교육하고, 134만 달러의 수출 상담을 달성했으며, 베트남 보건부로부터 의료 협력의 모범 사례로 인정받았습니다. KAT 베트남 2026은 그 기반 위에 구축됩니다.',
'idx.kat.btn':'KAT 2026 등록 →',
'idx.kat.2025':'KAT 베트남 2025',
'idx.kat.2025.detail':'Le Van Thinh 병원, 호치민시<br>의사 350명 · 수출 상담 134만 달러<br>베트남 보건부 인정',
'idx.kat.completed':'완료',
'idx.kat.china':'KAT 중국 2026',
'idx.kat.china.detail':'중국 · 상세 내용 추후 공개',
'idx.kat.coming':'출시 예정',
'idx.kat.2026':'KAT 베트남 2026',
'idx.kat.2026.detail':'10월 23일 (미정) · 호치민시<br>호치민시',
'idx.kat.regopen':'등록 진행 중',
'idx.kat.2027':'KAT 2027',
'idx.kat.2027.detail':'다음 개최지 — 추후 공개',
'idx.kat.staytune':'추후 공개',

// Stats
'idx.stats.eyb':'KAT 2025 — 검증된 실적',
'idx.stats.h2':'스스로 말하는<br>실적',
'idx.stats.desc':'KAT 2025는 베트남 보건부로부터 한·베 의료 협력의 모범 사례로 인정받았습니다. 국내 주요 언론이 다수 보도했습니다.',
'idx.stat1':'현장 교육 의사 수',
'idx.stat2':'수출 상담 실적',
'idx.stat3':'유통업체 후속 요청',
'idx.stat4':'병원 파트너십 요청',

// KOL
'idx.kol.eyb':'연사진',
'idx.kol.h2':'KSAPS & <em style="color:#5DCBA8;font-style:italic">SNUBH</em> 소속 한국 KOL 15인',
'idx.kol.more':'+ 9명 더 보기 →',

// Companies
'idx.co.eyb':'참가 기업',
'idx.co.h2':'학술대회 참가 한국 의료기기<br>기업 10개사',
'idx.co.desc':'KSAPS 학술대회 하노이 — 전시 부스 및 인더스트리 심포지엄. 1,000명 이상의 베트남 의료 전문가에게 한국 최신 미용 기술 직접 소개.',

// Policy
'idx.pol1.title':'무료 참가',
'idx.pol1.text':'모든 K-Beauty MEETS 행사는 베트남 의료 전문가에게 완전 무료입니다. KHIDI(한국보건산업진흥원) 지원, KSAPS, SNUBH, VSAPS, KBIT 공동 주최.',
'idx.pol2.title':'좌석 한정 · 심사 등록',
'idx.pol2.text':'좌석이 한정되어 있습니다. KBIT에서 3~5 영업일 이내에 심사합니다. 전문의(미용성형, 피부과, 성형외과) 우선.',
'idx.pol3.title':'불참 정책',
'idx.pol3.text':'참석이 불가능한 경우 사전에 secretary@kbitassociation.com으로 이메일을 보내주십시오. 사전 통보 없는 불참은 향후 KSAPS 및 KAT 행사 우선순위에 영향을 미칩니다.',

// Partners
'idx.partners':'파트너 & 후원',

// ===== SUMMIT PAGE =====
'sum.bc':'KSAPS 서밋',
'sum.tag':'Korea Meets VSAPS',
'sum.subtitle':'강남미용성형병원 호치민시에서의 집중 2일 워크숍 — 기자회견 · 학술 강연 · 라이브 기기 시연 · 라이브 수술 — 하루에 모두. 강연, OR에서의 라이브 수술 방송, 1:5 KOL 대 의사 비율의 소그룹 핸즈온.',
'sum.meta.date':'2026년 10월 3일',
'sum.meta.venue':'강남미용성형병원, 호치민시',
'sum.meta.docs':'의사 100명 · 1일',
'sum.meta.cert':'K-프로토콜 수료증',
'sum.btn.register':'지금 등록 — 무료',
'sum.btn.program':'프로그램 보기 ↓',
'sum.glance':'한눈에 보기',
'sum.stat1':'일 · 장소 2곳',
'sum.stat2':'최대 참가 인원',
'sum.stat3':'KOL 대 의사',
'sum.stat4':'한국 KOL',
'sum.included':'포함 내용',
'sum.inc1':'KSAPS & SNUBH 교수 강연',
'sum.inc2':'라이브 기기 시연 — 한국 기업 6개사',
'sum.inc3':'라이브 OR 수술 방송 (1일차)',
'sum.inc4':'3개 병행 핸즈온 트랙 (2일차)',
'sum.inc5':'K-프로토콜 수료증 + CME 수료증',
'sum.prog.eyb':'프로그램',
'sum.prog.h2':'2026년 10월 3일<br><em>종일 프로그램</em>',
'sum.prog.lead':'하루 집중 프로그램 — 오전 기자회견, 학술 강연, 오후 라이브 기기 시연, 마무리 라이브 비성형술 수술 방송.',
'sum.prog.morning':'오전',
'sum.prog.afternoon':'오후',
'sum.t1.title':'등록 & 네트워킹 커피',
'sum.t1.desc':'참가 등록 · 명찰 · 환영 다과',
'sum.t1.tag':'네트워킹',
'sum.t2.title':'개회식',
'sum.t2.desc':'환영사 — KSAPS · VSAPS · KBIT · 강남미용성형병원<br>단체 사진 · 한국 KOL 대표단 소개',
'sum.t2.tag':'개회',
'sum.t3.title':'기자회견',
'sum.t3.desc':'미디어 브리핑 — 행사 개요 및 주요 하이라이트<br>KSAPS · VSAPS · KBIT 대표 공동 성명<br>국내외 언론 초청 · 포토 타임',
'sum.t3.tag':'기자회견',
'sum.t4.title':'학술 강연 — 4개 세션 × 30분',
'sum.t4.tag':'학술 강연',
'sum.t4.l1':'강연 1 — HIFU & RF 복합 리프팅 프로토콜',
'sum.t4.l2':'강연 2 — 고급 비성형술: 한국 표준 2026',
'sum.t4.l3':'강연 3 — 실리프팅 & 고점도 필러 프로토콜',
'sum.t4.l4':'강연 4 — 재생 바이오필러 & SVF 임상 적용',
'sum.t5.title':'점심 & 네트워킹',
'sum.t5.desc':'뷔페 점심 · 한국 KOL과 베트남 의사 간 자유 네트워킹',
'sum.t5.tag':'휴식',
'sum.t6.title':'라이브 기기 시연 — 3개사 × 60분',
'sum.t6.desc':'각 기업이 환자 또는 모델에게 플래그십 기기를 라이브 시연 — 파라미터 가이드, 임상 프로토콜, Q&A 포함.',
'sum.t6.tag':'라이브 시연',
'sum.t6.c1':'기업 1 — 기기 시연',
'sum.t6.c1d':'미정 — HIFU / RF 플랫폼',
'sum.t6.c2':'기업 2 — 기기 시연',
'sum.t6.c2d':'미정 — 실리프팅 / 필러',
'sum.t6.c3':'기업 3 — 기기 시연',
'sum.t6.c3d':'미정 — 바이오필러 / 스킨 부스터',
'sum.t7.title':'라이브 수술 — 비성형술',
'sum.t7.desc':'KSAPS KOL이 시행하는 한국 표준 비성형술<br>OR에서 메인홀로 라이브 UHD 방송<br>전 과정 단계별 해설 · 실시간 Q&A<br>환자 사전 검사 및 동의 완료 · 베트남 마취팀 대기',
'sum.t7.tag':'라이브 수술 · OR 방송',
'sum.t8.title':'폐회식 & CME 수료증',
'sum.t8.desc':'폐회사 · CME 수료증 수여<br>KSAPS 학술대회 초대 — 10월 17–18일, 하노이',
'sum.t8.tag':'폐회 · CME 수료증',

// Venues
'sum.venue.eyb':'개최지',
'sum.venue.h2':'호치민시 최고의 민간 미용<br>성형 병원 2곳',
'sum.venue.lead':'두 곳 모두 세계적 수준의 수술실 시설, 방송 인프라, 한·베 의료 협력 실적을 기반으로 선정되었습니다. 컨퍼런스 호텔이 아닌 실제 환자를 치료하는 실제 병원입니다.',
'sum.v1.day':'1일차 · 10월 3일',
'sum.v1.loc':'호치민시, 베트남',
'sum.v1.b1':'호치민시 최대 민간 미용성형 병원 중 하나',
'sum.v1.b2':'HDMI/SDI 라이브 방송 시스템을 갖춘 수술실',
'sum.v1.b3':'50석 전용 세미나 공간 + 기기 시연 구역',
'sum.v1.b4':'한·베 시술 경험이 풍부한 팀',
'sum.v1.prog':'1일차 하이라이트',
'sum.v2.day':'2일차 · 10월 4일',
'sum.v2.loc':'호치민시, 베트남',
'sum.v2.b1':'호치민시 선도적 미용성형 병원 시스템',
'sum.v2.b2':'핸즈온 교육 스테이션 설치',
'sum.v2.b3':'50석 세미나실 + 전용 핸즈온 구역',
'sum.v2.b4':'KOL 네트워크를 제2 개최지로 확대',
'sum.v2.prog':'2일차 하이라이트',

// Devices
'sum.dev.eyb':'기기 & 기술',
'sum.dev.h2':'한국 기업 6개사.<br>하나의 임상 미션.',
'sum.dev.desc':'KSAPS 서밋에서 선보이는 모든 기기는 임상 프로토콜 개발에 참여한 KOL이 직접 시연합니다 — 기업 담당자나 트레이너가 아닌, 실제 진료에서 사용하는 한국 의사가 직접 보여줍니다.',
'sum.dev.list':'이 행사의 기기',

// KOL at Summit
'sum.kol.eyb':'연사진',
'sum.kol.h2':'KSAPS 서밋<br><em>한국 KOL</em>',
'sum.kol.lead':'이들은 초청 연사가 아닙니다 — 시연되는 임상 프로토콜을 직접 작성한 전문가입니다. 2일차 1:5 핸즈온에서 각 KOL과 직접, 개인적인 시간을 가질 수 있습니다.',
'sum.kol.more':'+ 2일차 핸즈온 트랙 KOL 4명 추가 ·',
'sum.kol.all':'전체 15명 연사 보기 →',

// Proof
'sum.proof.title':'검증된 형식 기반',
'sum.proof.desc':'핸즈온 서밋 형식은 KAT 2025에서 검증되고 개선되었습니다. 베트남 보건부는 이를 의료 협력의 모범 사례라 했습니다. KAT 2025 데이터는 한국 KOL이 베트남 의사와 직접 핸즈온할 때 무슨 일이 일어나는지 보여줍니다.',
'sum.proof.s1':'단일 KAT 행사에서 핸즈온 교육받은 의사',
'sum.proof.s2':'하루 수출 상담 실적',
'sum.proof.s3':'베트남 보건부 인정',
'sum.proof.s4':'서밋 + 학술대회 + KAT으로 확대',

// CTA
'sum.policy.title':'참석 정책',
'sum.policy.desc':'KSAPS 서밋은 베트남 의료 전문가 전원 무료입니다. KHIDI 지원, KSAPS, SNUBH, VSAPS, KBIT 공동 주최.',
'sum.policy.p1':'100석 — 엄격 심사. 양일 모두 신청 가능.',
'sum.policy.p2':'신청 후 3~5 영업일 이내 확인.',
'sum.policy.p3':'참석 불가 시 사전에 secretary@kbitassociation.com으로 이메일.',
'sum.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향.',
'sum.cta.title':'한국 최고의 전문가에게 배울 준비가 되셨습니까?',
'sum.cta.desc':'100석. 라이브 수술. 1:5 핸즈온. 10월 3일 강남미용성형병원, 호치민시.',
'sum.cta.btn':'지금 등록 — 무료 →',
'sum.cta.also':'10월 17–18일 하노이 학술대회 참가하시나요?',
'sum.cta.also2':'학술대회 & KAT 등록 →',

// ===== CONGRESS PAGE =====
'con.badge':'Korea Meets VSAPS · KSAPS 학술대회 2026',
'con.title':'K-Beauty MEETS의<br><em>플래그십</em><br>학술대회',
'con.desc':'베트남 최대 한·베 미용의학 교류 행사. 3개 병행 트랙, 1,000명 이상 참가, 15명 한국 KOL, K-이노베이션 파빌리온, VIP 갈라 디너 — 108 중앙군사병원에서 하루에 모두.',
'con.btn.register':'지금 등록 — 무료',
'con.btn.program':'프로그램 보기',
'con.stat.delegates':'참가자',
'con.stat.rooms':'종일 3개 병행 트랙',
'con.stat.kol':'발표 한국 KOL',
'con.stat.booths':'전시 부스',
'con.what.eyb':'KSAPS 학술대회란?',
'con.what.h2':'하루 종일<br>한국 미용 <em>의학</em>',
'con.what.p1':'KSAPS 학술대회 2026은 K-Beauty MEETS의 핵심 — 1,000명 이상의 베트남 의료 전문가와 15명의 한국 선도 미용 외과의 및 의사들이 만나는 종일 의학 학술대회입니다.',
'con.what.p2':'일반적인 학회와 달리, KSAPS 학술대회는 3개의 트랙을 동시에 운영하여 의료기기, 미용성형, 한국 임상 프로토콜 중 자신의 진료에 가장 적합한 트랙을 선택할 수 있습니다. 베트남에서 개최된 가장 포괄적인 한국 미용의학 행사입니다.',
'con.card1.title':'3개 병행 트랙 — 선택하세요',
'con.card1.desc':'Room A는 의료기기 및 에너지 기반 기술. Room B는 미용성형. Room C는 주사제 및 비수술 시술을 위한 한국 임상 프로토콜.',
'con.card2.title':'K-이노베이션 파빌리온',
'con.card2.desc':'한국 의료기기 기업 15개사 이상의 전시 구역. B2B 매칭, KOL 인증 사용자 프로그램, 유통 계약 LOI 체결.',
'con.card3.title':'VIP 갈라 디너',
'con.card3.desc':'10월 17일 저녁 150~200명 VIP 전용 네트워킹 디너. 전문의 및 학술대회 + KAT 콤보 등록자 우선.',
'con.card4.title':'CME 수료증',
'con.card4.desc':'KSAPS & KBIT 발행 KSAPS 학술대회 2026 수료증. 행사 후 CME 수료증 발급.',

// Program structure
'con.rooms.eyb':'프로그램 구성',
'con.rooms.h2':'3개 트랙. 종일.<br><em>깊이의 선택.</em>',
'con.rooms.lead':'3개의 완전한 병행 트랙이 종일 동시 운영됩니다. 트랙 간 이동도 하나에 집중도 가능 — 선택은 여러분의 몫입니다. 각 트랙은 독립적인 학습 경험으로 설계되었습니다.',
'con.ra.title':'의료기기',
'con.ra.sub':'EBD 마스터 클래스 · 인더스트리 심포지엄',
'con.ra.desc':'최신 한국 에너지 기반 의료기기 기술에 관심 있는 미용 의사를 위한 트랙. 각 세션은 임상 근거, 시술 파라미터, 실제 기기를 사용한 라이브 환자 시연을 다룹니다.',
'con.rb.title':'미용성형',
'con.rb.sub':'한국 수술 표준 · 라이브 케이스 토론',
'con.rb.desc':'최신 한국 수술 기법을 원하는 성형외과의 및 미용성형 외과의를 위한 트랙. 시술 표준, 합병증 관리, SNUBH 교수와의 복잡 케이스 토론.',
'con.rc.title':'한국 프로토콜',
'con.rc.sub':'주사제 · 비수술 · 패널 Q&A',
'con.rc.desc':'비수술 시술에 초점을 맞춘 피부과 및 미용 의사를 위한 트랙. 모든 세션은 프로토콜 중심 — 한국 의사들이 실제로 어떻게 하는지, 베트남 환자와 진료 환경에 맞게 적용.',

// Full program
'con.sched.eyb':'전체 프로그램',
'con.sched.h2':'2026년 10월 17–18일 —<br><em>2일</em>',
'con.d1':'1일차 · 토요일, 10월 17일',
'con.d1.sub':'학술 세션 · 3개 병행 트랙 · 전시 · 갈라 디너',
'con.d2':'2일차 · 일요일, 10월 18일',
'con.d2.sub':'핸즈온 워크숍 · 라이브 수술 · CME 수료증',

// Congress KOL
'con.kol.eyb':'연사진',
'con.kol.h2':'학술대회 발표<br><em>한국 KOL</em>',

// Congress Policy
'con.policy.title':'참석 정책',
'con.policy.desc':'KSAPS 학술대회는 베트남 의료 전문가 전원 무료 — KHIDI 지원. 좌석 한정, KBIT 조직위원회 심사.',
'con.policy.p1':'신청 후 3~5 영업일 이내 확인',
'con.policy.p2':'갈라 디너 별도 심사 — 전문의 및 콤보 등록자 우선',
'con.policy.p3':'참석 불가 시 사전에 이메일 — secretary@kbitassociation.com',
'con.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향',
'con.cta.title':'KSAPS 학술대회 2026 참가',
'con.cta.desc':'10월 17일 · 108 중앙군사병원<br>호치민시, 베트남<br>무료 참가 · 좌석 한정 · 심사 기반',
'con.cta.btn':'지금 등록 — 무료 →',
'con.cta.also':'다음 날 참가하시나요?',
'con.cta.also2':'KAT 베트남 10월 23일 등록 →',

// ===== KAT PAGE =====
'kat.tag':'KAT · K-Beauty Advanced Skills Training',
'kat.subtitle':'— 시리즈 중 가장 실용적인 교육의 날. 강연 없음. 순수 한국 기술을 베트남 의사에게 직접 전수 — 라이브 수술, 라이브 기기 시연, 1:5 라이브 관찰 및 Q&A.',
'kat.meta.date':'2026년 10월 23일 (미정)',
'kat.meta.venue':'호치민시',
'kat.meta.type':'독립 행사',
'kat.meta.surgery':'라이브 수술 4건',
'kat.btn.register':'지금 등록 — 무료',
'kat.btn.schedule':'일정 보기 ↓',
'kat.glance':'한눈에 보기',
'kat.stat1':'의사',
'kat.stat2':'병행 트랙',
'kat.stat3':'라이브 수술 건수',
'kat.stat4':'KOL 대 의사',
'kat.included':'포함 내용',
'kat.inc1':'Room A: RF, HIFU, 피코 레이저 라이브 시연',
'kat.inc2':'보톡스 & 필러 핸즈온 (한국 KOL 직접 지도)',
'kat.inc3':'Room B: 라이브 비성형술, 안검성형, SVF',
'kat.inc4':'KAT 2026 수료증 — KSAPS + KBIT',
'kat.inc5':'CME 수료증 발급',
'kat.what.eyb':'KAT의 차별점',
'kat.what.h2':'이론이 아닌, <em style="color:#F0C060">실습.</em>',
'kat.what.lead':'KAT 베트남 2026은 전날의 학술대회와 의도적으로 다릅니다. 학술대회가 3개 트랙에서 학문적 폭을 제공한다면, KAT은 한 방향으로 깊이 들어갑니다: 듣기만 한 것이 아니라 직접 해본 경험을 가지고 떠나는 것.',
'kat.wc1.title':'실시간 라이브 수술',
'kat.wc1.desc':'Room B에서 OR에서 직접 4건의 라이브 성형수술을 방송합니다. 각 건에는 수술 중인 한국 외과의의 단계별 해설과 청중의 실시간 Q&A가 포함됩니다. 녹화가 아닙니다 — 실제로 일어나는 것을 보는 것입니다.',
'kat.wc2.title':'한국 KOL 직접 지도 핸즈온',
'kat.wc2.desc':'Room A에서 종일 소그룹 핸즈온 세션 운영 — 베트남 의사 5명당 한국 KOL 1명. 각 그룹은 RF/HIFU 기기의 직접 파라미터 지도와 모델에 대한 보톡스 및 필러 주사 실습을 받습니다. 시범이 아닌 실제 실습입니다.',
'kat.wc3.title':'2일 여정의 2일차',
'kat.wc3.desc':'KAT 베트남은 KSAPS 학술대회(10월 17–18일)의 직접적인 후속 프로그램으로 설계되었습니다. 양쪽 모두 참석하면 베트남에서 가능한 가장 집중적인 한국 미용의학 교육 이틀을 경험합니다 — 각 행사별 별도 CME 수료증.',

// ===== REGISTER PAGE (unified) =====
'reg.eyebrow':'K-Beauty MEETS 2026 · 등록',
'reg.sub':'하나의 양식. 하나, 둘, 또는 세 개 행사를 선택하세요. 정보를 한 번만 입력하면 — KBIT이 신청을 검토하고 확인된 각 행사에 대해 별도의 QR 티켓을 발급합니다.',
'reg.step1':'행사 선택',
'reg.step2':'상세정보',
'reg.step3':'관심 분야',
'reg.step4':'확인',
'reg.ev.title':'어떤 행사에 참석하시겠습니까?',
'reg.ev.sub':'하나, 둘, 또는 세 개를 선택하세요. 정보를 한 번만 입력하면 — KBIT이 검토 후 확인된 각 행사에 대해 별도의 QR 티켓을 보내드립니다.',
'reg.next':'상세정보 입력으로 →',
'reg.personal':'개인 정보',
'reg.fname':'이름 (성명) <span class="req">*</span>',
'reg.phone':'전화번호 <span class="req">*</span>',
'reg.email':'이메일 주소 <span class="req">*</span>',
'reg.cme':'CME 번호 / 의사면허',
'reg.hospital':'병원 / 클리닉 이름 <span class="req">*</span>',
'reg.city':'도시 <span class="req">*</span>',
'reg.specialty':'전공 <span class="req">*</span>',
'reg.experience':'경력 <span class="req">*</span>',
'reg.topics':'관심 분야',
'reg.goals':'K-Beauty MEETS에서 얻고 싶은 것은?',
'reg.policy.title':'참석 정책 — 제출 전 반드시 읽어주세요',
'reg.policy.p1':'무료 참가 — 행사당 좌석 한정. 등록이 참석을 보장하지 않습니다. <strong>등록 마감: 2026년 9월 26일.</strong>',
'reg.policy.p2':'확인 이메일은 3~5 영업일 이내 발송됩니다.',
'reg.policy.p3':'참석 불가 시 사전에 secretary@kbitassociation.com으로 이메일을 보내주세요.',
'reg.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향을 미칩니다.',
'reg.agree':'참석 정책을 읽었으며 동의합니다. 참석이 불가능한 경우 조직위원회에 통보할 것을 약속합니다.',
'reg.submit':'신청서 제출 →',
'reg.qr.title':'1개 양식 · 최대 3개 QR 티켓',
'reg.qr.sub':'KBIT이 확인된 각 행사에 대해 별도의 QR 티켓을 발급합니다. 당일 QR을 지참하여 체크인하세요.',
'reg.selected':'선택한 행사',
'reg.side.included':'포함 내용',
'reg.side.questions':'문의',
'reg.success.title':'등록이 완료되었습니다!',
'reg.success.code':'등록 코드:',
'reg.success.msg':'신청서를 검토하고 3~5 영업일 이내에 확인 이메일을 보내드리겠습니다.<br>체크인을 위해 등록 코드를 저장해 주세요.',
'reg.success.back':'홈페이지로 돌아가기',

// ===== SPEAKERS PAGE =====
'spk.eyb':'K-Beauty MEETS 2026',
'spk.title':'베트남에 오는<br>한국 KOL 15인',
'spk.desc':'한국에서 가장 존경받는 미용 외과의와 의사들 — KSAPS와 SNUBH 소속 — 수십 년의 임상 경험을 호치민시의 세 개 행사에 직접 가져옵니다.',
'spk.filter.all':'전체 KOL',
'spk.filter.summit':'서밋',
'spk.filter.congress':'학술대회',
'spk.filter.kat':'KAT',
'spk.filter.surgery':'수술',
'spk.filter.devices':'기기',
'spk.specialty':'전공 & 주제',
'spk.events':'참가 행사',
'spk.more':'추가 KOL 7명',
'spk.more.sub':'핸즈온 트랙 강사',
'spk.coverage':'담당 분야',

// VSAPS section
'spk.vsaps.eyb':'베트남 파트너',
'spk.vsaps.h2':'VSAPS —<br>베트남 미용성형<br>외과의로의 <em>관문</em>',
'spk.vsaps.p1':'베트남미용성형외과학회(VSAPS)는 K-Beauty MEETS 2026의 공식 베트남 파트너입니다. 2007년에 설립되어 베트남 보건부의 인정을 받은 VSAPS는 베트남 미용성형의 중심 조직입니다.',
'spk.vsaps.p2':'KSAPS-VSAPS 파트너십 MOU는 2026년 4월 서울에서 열린 APS Korea 2026에서 체결되었습니다 — VSAPS 회장 Dr. Lê Hành과 23명의 VSAPS 이사회 멤버가 참석했습니다. 이를 통해 K-Beauty MEETS는 베트남 전체 미용성형 커뮤니티에 직접 접근할 수 있게 되었습니다.',
'spk.vsaps.s1':'베트남 미용성형 외과의의',
'spk.vsaps.s1b':'이상이 VSAPS 회원',
'spk.vsaps.s2':'활동 회원 의사 — 모두 임상 의사결정자',
'spk.vsaps.s3':'설립 · 베트남 보건부 인정',
'spk.vsaps.s4':'연례 학술대회 10회 달성 — 2026',

// CTA
'spk.cta.eyb':'K-Beauty MEETS 2026',
'spk.cta.title':'호치민시에서 이 의사들을 만나세요',
'spk.cta.desc':'15명의 한국 KOL이 세 개 행사에서 발표, 시연, 교육합니다 — 베트남 의료 전문가 전원 무료.',
'spk.cta.summit':'서밋 등록',
'spk.cta.congress':'학술대회 등록',
'spk.cta.kat':'KAT 등록',

// ===== BUSINESS MEETING PAGE =====
'biz.eyb':'비즈니스 미팅 프로그램',
'biz.h2':'베트남 최고의<br><em>미용 클리닉</em>에 대한 체계적 접근',
'biz.lead':'비즈니스 미팅 프로그램은 한국 의료기기 기업에게 K-Beauty MEETS 행사에 참석하는 베트남 병원장, 클리닉 원장, 구매 관리자와의 직접 예약 1:1 미팅을 제공합니다. KBIT이 매칭과 일정을 조율합니다.',
'biz.wc1.title':'맞춤형 1:1 매칭',
'biz.wc1.desc':'KBIT이 귀사의 기업 프로필과 미팅 목표를 검토한 후, 사전 검증된 베트남 바이어 — 행사에 참석하는 병원장, 클리닉 원장, 의료장비 구매 관리자 — 와 매칭합니다.',
'biz.wc2.title':'사전 확인 & 예약',
'biz.wc2.desc':'각 행사 점심 및 커피 브레이크 시간 중 30분 전용 세션. 모든 미팅 양측 사전 확인. 전담 통역 제공. 구매 의사가 있는 경우 현장 LOI 체결 지원.',
'biz.wc3.title':'3개 행사 · 2개 도시',
'biz.wc3.desc':'1개, 2개, 또는 3개 행사 모두 등록 가능. 각 행사는 베트남 미용의학 시장의 다른 세그먼트에 접근 — 서밋과 KAT의 호치민시 전문의, 학술대회의 하노이 및 전국 참가자.',
'biz.side.title':'3개 행사 · 2개 도시',
'biz.side.summit':'서밋 + KAT',
'biz.side.congress':'학술대회',
'biz.side.reach':'총 접근 규모',
'biz.side.reachval':'의료 전문가 1,200명 이상',
'biz.side.reachsub':'전체 3개 행사 합산',
'biz.side.provides':'KBIT 제공 서비스',
'biz.side.prov1':'바이어 매칭 & 사전 일정',
'biz.side.prov2':'한국어 ↔ 베트남어 통역',
'biz.side.prov3':'행사장 내 미팅룸 / 공간',
'biz.side.prov4':'LOI 문서 지원',
'biz.side.prov5':'행사 후 후속 조치 지원',
'biz.side.prov6':'수출 상담 보고서',
'biz.side.questions':'문의',
};
