window.KO={
// ===== SHARED NAV =====
'nav.summit':'서밋',
'nav.congress':'학술대회',
'nav.kat':'KAT',
'nav.speakers':'연사진',
'nav.business':'비즈니스',
'nav.register':'무료 등록',
'nav.reg':'등록',
'nav.library':'라이브러리',
'nav.regmeet':'미팅 등록',

// ===== SHARED FOOTER =====
'ft.events':'행사',
'ft.register':'등록',
'ft.more':'더보기',
'ft.speakers':'연사진',
'ft.contact':'KBIT 문의',
'ft.copy':'© 2026 K-Beauty MEETS · KBIT 주관',
'ft.tagline':'K-Beauty · Medical · Excellence · Exchange · Training · Skills<br>호치민시 + 하노이 · 2026년 10월',
'ft.reg.summit':'서밋 등록',
'ft.reg.kat':'KAT 등록',
'ft.reg.congress':'학술대회 등록',
'ft.ev.summit':'KSAPS 서밋 · 10월 3일 · 호치민시',
'ft.ev.kat':'KAT 베트남 2026 · 10월 4일 · 호치민시 ',
'ft.ev.congress':'KSAPS 학술대회 · 10월 17–18일 · 하노이',

// ===== INDEX PAGE =====
'idx.supported':'후원',
'idx.organized':'주최',
'idx.khidi':'KHIDI',
'idx.mohw':'대한민국 보건복지부',
'idx.eyebrow':'호치민시 & 하노이, 베트남 · 2026년 10월',
'idx.sub':'K-Beauty · Medical · Excellence · Exchange · Training · Skills',
'idx.tagline':'한국의 우수한 의료기술이 아시아를 만나다',
'idx.btn.summit':'서밋 둘러보기 →',
'idx.btn.congress':'학술대회 등록 →',
'idx.btn.kat':'KAT 등록',
'idx.hd.summit':'KSAPS 서밋',
'idx.hd.kat':'KAT 베트남',
'idx.hd.congress':'KSAPS 학술대회',
'idx.hd.hcmc':'호치민시',
'idx.hd.hanoi':'하노이',

// What is K-Beauty MEETS
'idx.meets.eyb':'K-Beauty MEETS란?',
'idx.meets.h2':'학회 그 이상 —<br>의료 <em style="color:#5DCBA8;font-style:italic">혁신의 움직임</em>',
'idx.meets.desc':'K-Beauty MEETS는 베트남 최고의 미용의학 전문의들이 한국의 저명한 KOL과 직접 교류하는 프로그램입니다 — 라이브 수술, 기기 시연, 실습을 통해 호치민시와 하노이의 세계적 수준의 병원에서 진행됩니다.',
'idx.mc.kbeauty':'K-Beauty',
'idx.mc.kpill':'한국<br>미용의학 기준',
'idx.mc.medical':'Medical',
'idx.mc.excellence':'Excellence',
'idx.mc.epill':'15명 KOL<br>K-스탠다드 프로토콜',
'idx.mc.exchange':'Exchange',
'idx.mc.expill':'KOL<br>Q&A 패널',
'idx.mc.training':'Training',
'idx.mc.tpill':'학술대회 · CME<br>핸즈온',
'idx.mc.skills':'Skills',
'idx.mc.spill':'KAT<br>라이브 수술',

// Why K-Beauty MEETS
'idx.why.eyb':'왜 K-Beauty MEETS인가?',
'idx.why.h2':'기준이 바뀌었습니다.<br><em>준비되셨습니까?</em>',
'idx.why.lead':'한국 미용의학은 세계를 선도합니다. K-Beauty MEETS는 베트남 의사들에게 그 기준을 이끄는 전문가, 프로토콜, 기기에 직접 접근할 수 있는 기회를 제공합니다 — 교과서가 아닌 자신의 도시에서의 실습 경험을 통해.',
'idx.why1.title':'한국 KOL 직접 교류',
'idx.why1.desc':'KSAPS와 SNUBH 소속 15명의 핵심 오피니언 리더(KOL) — 한국에서 가장 존경받는 미용성형 학회입니다. 녹화된 강의가 아닙니다. 실제 외과의와 의사들이 여러분과 같은 공간에서 수술하고 실시간으로 질문에 답합니다.',
'idx.why2.title':'이론이 아닌 K-스탠다드 프로토콜',
'idx.why2.desc':'라이브 기기 시연. 라이브 수술 방송. 1:5 소그룹 핸즈온. 모든 세션은 임상 적용 중심으로 설계되었습니다 — 베트남 환자에 맞게 조정된, 클리닉에서 즉시 사용할 수 있는 프로토콜.',
'idx.why3.title':'정부 지원, 무료 참가',
'idx.why3.desc':'보건복지부 산하 한국보건산업진흥원(KHIDI) 지원. 모든 행사는 베트남 의료 전문가에게 무료입니다. 좌석 한정, 심사 기반 등록.',

// 2026 Series
'idx.ev.eyb':'2026 시리즈',
'idx.ev.h2':'두 도시. 세 개의 행사.<br>하나의 <em style="color:#5DCBA8;font-style:italic">움직임.</em>',
'idx.ev.desc':'호치민시의 집중 임상 워크숍부터 하노이의 베트남 최대 한국 미용의학 학술대회까지 — K-Beauty MEETS 2026은 두 도시, 나흘에 걸쳐 진행됩니다.',
'idx.ec.summit.badge':'Korea Meets VSAPS · 호치민시',
'idx.ec.summit.theme':'"Korean Beauty — 미용성형 및 의료기기 최신 동향"',
'idx.ec.summit.meta':'2026년 10월 3일 · 강남미용성형병원',
'idx.ec.summit.b1':'의사 100명 · 1일 · 호치민시',
'idx.ec.summit.b2':'기자회견 · 강연 · 라이브 기기 시연 · 라이브 수술',
'idx.ec.summit.b4':'K-프로토콜 수료증',
'idx.ec.summit.desc':'강남미용성형병원에서의 집중 2일 워크숍 — 베트남 최고의 민간 미용성형 시설. 1일차: 강연 및 라이브 기기 시연. 2일차: 기자회견, 라이브 수술 방송, 보톡스/필러/실리프팅 핸즈온 교육.',
'idx.ec.summit.free':'<strong>무료</strong> · 100명 한정',
'idx.ec.learn':'자세히 보기',
'idx.ec.kat.badge':'KAT · 호치민시',
'idx.ec.kat.theme':'"당신의 손. 한국의 기술."',
'idx.ec.kat.meta':'2026년 10월 4일  · 호치민시',
'idx.ec.kat.b1':'독립 행사 2일차',
'idx.ec.kat.b2':'라이브 기기 시연 · 보톡스 & 필러 라이브 · 라이브 성형수술',
'idx.ec.kat.b3':'라이브 성형수술',
'idx.ec.kat.b4':'KAT 2026 수료증',
'idx.ec.kat.desc':'K-Beauty Advanced Skills Training — 공동 주최. 순수 기술 전수: OR에서의 라이브 수술, 기기 시연, 한국 KOL 지도 아래 보톡스 및 필러 직접 실습.',
'idx.ec.kat.free':'<strong>무료</strong> · 좌석 한정',
'idx.ec.congress.badge':'Korea Meets VSAPS · 하노이',
'idx.ec.congress.theme':'"Korean Beauty — 최첨단 미용성형 및 의료 기술"',
'idx.ec.congress.meta':'2026년 10월 17–18일 · 108 중앙군사병원, 하노이',
'idx.ec.congress.b1':'약 1,000명 참가 · 2일 · 하노이',
'idx.ec.congress.b2':'학술 세션 + 3개 병행 트랙',
'idx.ec.congress.b3':'한국 기업 10개사 전시',
'idx.ec.congress.b4':'핸즈온 워크숍 + 갈라 디너',
'idx.ec.congress.desc':'베트남 최대 한·베 미용의학 학술대회. 하노이 108 중앙군사병원에서 이틀간 — 학술 세션, 병행 트랙, 10개사 전시, 라이브 수술, 핸즈온 교육, VIP 갈라 디너.',
'idx.ec.congress.free':'<strong>무료</strong> · 좌석 한정',

// KAT Timeline
'idx.kat.eyb':'KAT',
'idx.kat.h2':'한국의 교육 시리즈 —<br><em>아시아로 확장</em>',
'idx.kat.lead':'KAT — K-Beauty Advanced Skills Training — 한국 KOL이 현지 의사들에게 직접 실습 기술을 전수합니다. 매년 새로운 아시아 도시. 매 회차마다 더 깊어지는 한국 교육 미용 전문가 네트워크.',
'idx.kat.desc2':'KAT 2025는 350명의 의사를 교육하고, 134만 달러의 수출 상담을 달성했으며, 베트남 보건부로부터 의료 협력의 모범 사례로 인정받았습니다. KAT 베트남 2026은 그 기반 위에 구축됩니다.',
'idx.kat.btn':'KAT 2026 등록 →',
'idx.kat.2025':'KAT 베트남 2025',
'idx.kat.2025.detail':'Le Van Thinh 병원, 호치민시<br>의사 350명 · 수출 상담 134만 달러<br>베트남 보건부 인정',
'idx.kat.completed':'완료',
'idx.kat.china':'KAT 중국 2026',
'idx.kat.china.detail':'중국 · 상세 내용 추후 공개',
'idx.kat.coming':'출시 예정',
'idx.kat.2026':'KAT 베트남 2026',
'idx.kat.2026.detail':'10월 4일  · 호치민시<br>호치민시',
'idx.kat.regopen':'등록 진행 중',
'idx.kat.2027':'KAT 2027',
'idx.kat.2027.detail':'다음 개최지 — 추후 공개',
'idx.kat.staytune':'추후 공개',

// Stats
'idx.stats.eyb':'KAT 2025 — 검증된 실적',
'idx.stats.h2':'스스로 말하는<br>실적',
'idx.stats.desc':'KAT 2025는 베트남 보건부로부터 한·베 의료 협력의 모범 사례로 인정받았습니다. 국내 주요 언론이 다수 보도했습니다.',
'idx.stat1':'현장 교육 의사 수',
'idx.stat2':'수출 상담 실적',
'idx.stat3':'유통업체 후속 요청',
'idx.stat4':'병원 파트너십 요청',

// KOL
'idx.kol.eyb':'연사진',
'idx.kol.h2':'KSAPS & <em style="color:#5DCBA8;font-style:italic">SNUBH</em> 소속 한국 KOL 15인',
'idx.kol.more':'+ 9명 더 보기 →',

// Companies
'idx.co.eyb':'참가 기업',
'idx.co.h2':'학술대회 참가 한국 의료기기<br>기업 10개사',
'idx.co.desc':'KSAPS 학술대회 하노이 — 전시 부스 및 인더스트리 심포지엄. 1,000명 이상의 베트남 의료 전문가에게 한국 최신 미용 기술 직접 소개.',

// Policy
'idx.pol1.title':'무료 참가',
'idx.pol1.text':'모든 K-Beauty MEETS 행사는 베트남 의료 전문가에게 완전 무료입니다. KHIDI(한국보건산업진흥원) 지원, KSAPS, SNUBH, VSAPS, KBIT 공동 주최.',
'idx.pol2.title':'좌석 한정 · 심사 등록',
'idx.pol2.text':'좌석이 한정되어 있습니다. KBIT에서 3~5 영업일 이내에 심사합니다. 전문의(미용성형, 피부과, 성형외과) 우선.',
'idx.pol3.title':'불참 정책',
'idx.pol3.text':'참석이 불가능한 경우 사전에 secretary@kbitassociation.com으로 이메일을 보내주십시오. 사전 통보 없는 불참은 향후 KSAPS 및 KAT 행사 우선순위에 영향을 미칩니다.',

// Partners
'idx.partners':'파트너 & 후원',

// ===== SUMMIT PAGE =====
'sum.bc':'KSAPS 서밋',
'sum.tag':'Korea Meets VSAPS',
'sum.subtitle':'강남미용성형병원 호치민시에서의 집중 2일 워크숍 — 기자회견 · 학술 강연 · 라이브 기기 시연 · 라이브 수술 — 하루에 모두. 강연, OR에서의 라이브 수술 방송, 1:5 KOL 대 의사 비율의 소그룹 핸즈온.',
'sum.meta.date':'2026년 10월 3일',
'sum.meta.venue':'강남미용성형병원, 호치민시',
'sum.meta.docs':'의사 100명 · 1일',
'sum.meta.cert':'K-프로토콜 수료증',
'sum.btn.register':'지금 등록 — 무료',
'sum.btn.program':'프로그램 보기 ↓',
'sum.glance':'한눈에 보기',
'sum.stat1':'일 · 장소 2곳',
'sum.stat2':'최대 참가 인원',
'sum.stat3':'KOL 대 의사',
'sum.stat4':'한국 KOL',
'sum.included':'포함 내용',
'sum.inc1':'KSAPS & SNUBH 교수 강연',
'sum.inc2':'라이브 기기 시연 — 한국 기업 6개사',
'sum.inc3':'라이브 OR 수술 방송 (1일차)',
'sum.inc4':'3개 병행 핸즈온 트랙 (2일차)',
'sum.inc5':'K-프로토콜 수료증',
'sum.prog.eyb':'프로그램',
'sum.prog.h2':'2026년 10월 3일<br><em>종일 프로그램</em>',
'sum.prog.lead':'하루 집중 프로그램 — 오전 기자회견, 학술 강연, 오후 라이브 기기 시연, 마무리 라이브 비성형술 수술 방송.',
'sum.prog.morning':'오전',
'sum.prog.afternoon':'오후',
'sum.t1.title':'등록 & 네트워킹 커피',
'sum.t1.desc':'참가 등록 · 명찰 · 환영 다과',
'sum.t1.tag':'네트워킹',
'sum.t2.title':'개회식',
'sum.t2.desc':'환영사 — KSAPS · VSAPS · KBIT · 강남미용성형병원<br>단체 사진 · 한국 KOL 대표단 소개',
'sum.t2.tag':'개회',
'sum.t3.title':'기자회견',
'sum.t3.desc':'미디어 브리핑 — 행사 개요 및 주요 하이라이트<br>KSAPS · VSAPS · KBIT 대표 공동 성명<br>국내외 언론 초청 · 포토 타임',
'sum.t3.tag':'기자회견',
'sum.t4.title':'학술 강연 — 4개 세션 × 30분',
'sum.t4.tag':'학술 강연',
'sum.t4.l1':'강연 1 — HIFU & RF 복합 리프팅 프로토콜',
'sum.t4.l2':'강연 2 — 고급 비성형술: 한국 표준 2026',
'sum.t4.l3':'강연 3 — 실리프팅 & 고점도 필러 프로토콜',
'sum.t4.l4':'강연 4 — 재생 바이오필러 & SVF 임상 적용',
'sum.t5.title':'점심 & 네트워킹',
'sum.t5.desc':'뷔페 점심 · 한국 KOL과 베트남 의사 간 자유 네트워킹',
'sum.t5.tag':'휴식',
'sum.t6.title':'라이브 기기 시연 — 3개사 × 60분',
'sum.t6.desc':'각 기업이 환자 또는 모델에게 플래그십 기기를 라이브 시연 — 파라미터 가이드, 임상 프로토콜, Q&A 포함.',
'sum.t6.tag':'라이브 시연',
'sum.t6.c1':'기업 1 — 기기 시연',
'sum.t6.c1d':'미정 — HIFU / RF 플랫폼',
'sum.t6.c2':'기업 2 — 기기 시연',
'sum.t6.c2d':'미정 — 실리프팅 / 필러',
'sum.t6.c3':'기업 3 — 기기 시연',
'sum.t6.c3d':'미정 — 바이오필러 / 스킨 부스터',
'sum.t7.title':'라이브 수술 — 비성형술',
'sum.t7.desc':'KSAPS KOL이 시행하는 한국 표준 비성형술<br>OR에서 메인홀로 라이브 UHD 방송<br>전 과정 단계별 해설 · 실시간 Q&A<br>환자 사전 검사 및 동의 완료 · 베트남 마취팀 대기',
'sum.t7.tag':'라이브 수술 · OR 방송',
'sum.t8.title':'폐회식 & 수료증 수여',
'sum.t8.desc':'폐회사 · 수료증 수여<br>KSAPS 학술대회 초대 — 10월 17–18일, 하노이',
'sum.t8.tag':'폐회 · 수료증',

// Venues
'sum.venue.eyb':'개최지',
'sum.venue.h2':'호치민시 최고의 민간 미용<br>성형 병원 2곳',
'sum.venue.lead':'두 곳 모두 세계적 수준의 수술실 시설, 방송 인프라, 한·베 의료 협력 실적을 기반으로 선정되었습니다. 컨퍼런스 호텔이 아닌 실제 환자를 치료하는 실제 병원입니다.',
'sum.v1.day':'1일차 · 10월 3일',
'sum.v1.loc':'호치민시, 베트남',
'sum.v1.b1':'호치민시 최대 민간 미용성형 병원 중 하나',
'sum.v1.b2':'HDMI/SDI 라이브 방송 시스템을 갖춘 수술실',
'sum.v1.b3':'50석 전용 세미나 공간 + 기기 시연 구역',
'sum.v1.b4':'한·베 시술 경험이 풍부한 팀',
'sum.v1.prog':'1일차 하이라이트',
'sum.v2.day':'2일차 · 10월 4일',
'sum.v2.loc':'호치민시, 베트남',
'sum.v2.b1':'호치민시 선도적 미용성형 병원 시스템',
'sum.v2.b2':'핸즈온 교육 스테이션 설치',
'sum.v2.b3':'50석 세미나실 + 전용 핸즈온 구역',
'sum.v2.b4':'KOL 네트워크를 제2 개최지로 확대',
'sum.v2.prog':'2일차 하이라이트',

// Devices
'sum.dev.eyb':'기기 & 기술',
'sum.dev.h2':'한국 기업 6개사.<br>하나의 임상 미션.',
'sum.dev.desc':'KSAPS 서밋에서 선보이는 모든 기기는 임상 프로토콜 개발에 참여한 KOL이 직접 시연합니다 — 기업 담당자나 트레이너가 아닌, 실제 진료에서 사용하는 한국 의사가 직접 보여줍니다.',
'sum.dev.list':'이 행사의 기기',

// KOL at Summit
'sum.kol.eyb':'연사진',
'sum.kol.h2':'KSAPS 서밋<br><em>한국 KOL</em>',
'sum.kol.lead':'이들은 초청 연사가 아닙니다 — 시연되는 임상 프로토콜을 직접 작성한 전문가입니다. 2일차 1:5 핸즈온에서 각 KOL과 직접, 개인적인 시간을 가질 수 있습니다.',
'sum.kol.more':'+ 2일차 핸즈온 트랙 KOL 4명 추가 ·',
'sum.kol.all':'전체 15명 연사 보기 →',

// Proof
'sum.proof.title':'검증된 형식 기반',
'sum.proof.desc':'핸즈온 서밋 형식은 KAT 2025에서 검증되고 개선되었습니다. 베트남 보건부는 이를 의료 협력의 모범 사례라 했습니다. KAT 2025 데이터는 한국 KOL이 베트남 의사와 직접 핸즈온할 때 무슨 일이 일어나는지 보여줍니다.',
'sum.proof.s1':'단일 KAT 행사에서 핸즈온 교육받은 의사',
'sum.proof.s2':'하루 수출 상담 실적',
'sum.proof.s3':'베트남 보건부 인정',
'sum.proof.s4':'서밋 + 학술대회 + KAT으로 확대',

// CTA
'sum.policy.title':'참석 정책',
'sum.policy.desc':'KSAPS 서밋은 베트남 의료 전문가 전원 무료입니다. KHIDI 지원, KSAPS, SNUBH, VSAPS, KBIT 공동 주최.',
'sum.policy.p1':'100석 — 엄격 심사. 양일 모두 신청 가능.',
'sum.policy.p2':'신청 후 3~5 영업일 이내 확인.',
'sum.policy.p3':'참석 불가 시 사전에 secretary@kbitassociation.com으로 이메일.',
'sum.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향.',
'sum.cta.title':'한국 최고의 전문가에게 배울 준비가 되셨습니까?',
'sum.cta.desc':'100석. 라이브 수술. 1:5 핸즈온. 10월 3일 강남미용성형병원, 호치민시.',
'sum.cta.btn':'지금 등록 — 무료 →',
'sum.cta.also':'10월 17–18일 하노이 학술대회 참가하시나요?',
'sum.cta.also2':'학술대회 & KAT 등록 →',

// ===== CONGRESS PAGE =====
'con.badge':'Korea Meets VSAPS · KSAPS 학술대회 2026',
'con.title':'K-Beauty MEETS의<br><em>플래그십</em><br>학술대회',
'con.desc':'베트남 최대 한·베 미용의학 교류 행사. 3개 병행 트랙, 1,000명 이상 참가, 15명 한국 KOL, K-이노베이션 파빌리온, VIP 갈라 디너 — 108 중앙군사병원에서 하루에 모두.',
'con.btn.register':'지금 등록 — 무료',
'con.btn.program':'프로그램 보기',
'con.stat.delegates':'참가자',
'con.stat.rooms':'종일 3개 병행 트랙',
'con.stat.kol':'발표 한국 KOL',
'con.stat.booths':'전시 부스',
'con.what.eyb':'KSAPS 학술대회란?',
'con.what.h2':'하루 종일<br>한국 미용 <em>의학</em>',
'con.what.p1':'KSAPS 학술대회 2026은 K-Beauty MEETS의 핵심 — 1,000명 이상의 베트남 의료 전문가와 15명의 한국 선도 미용 외과의 및 의사들이 만나는 종일 의학 학술대회입니다.',
'con.what.p2':'일반적인 학회와 달리, KSAPS 학술대회는 3개의 트랙을 동시에 운영하여 의료기기, 미용성형, 한국 임상 프로토콜 중 자신의 진료에 가장 적합한 트랙을 선택할 수 있습니다. 베트남에서 개최된 가장 포괄적인 한국 미용의학 행사입니다.',
'con.card1.title':'3개 병행 트랙 — 선택하세요',
'con.card1.desc':'Room A는 의료기기 및 에너지 기반 기술. Room B는 미용성형. Room C는 주사제 및 비수술 시술을 위한 한국 임상 프로토콜.',
'con.card2.title':'K-이노베이션 파빌리온',
'con.card2.desc':'한국 의료기기 기업 15개사 이상의 전시 구역. B2B 매칭, KOL 인증 사용자 프로그램, 유통 계약 LOI 체결.',
'con.card3.title':'VIP 갈라 디너',
'con.card3.desc':'10월 17일 저녁 150~200명 VIP 전용 네트워킹 디너. 전문의 및 학술대회 + KAT 콤보 등록자 우선.',
'con.card4.title':'CME 수료증 (350,000₫/인)',
'con.card4.desc':'KSAPS & KBIT 발행 KSAPS 학술대회 2026 수료증. 행사 후 CME 수료증 발급. 비용: 350,000₫/인.',

// Program structure
'con.rooms.eyb':'프로그램 구성',
'con.rooms.h2':'3개 트랙. 종일.<br><em>깊이의 선택.</em>',
'con.rooms.lead':'3개의 완전한 병행 트랙이 종일 동시 운영됩니다. 트랙 간 이동도 하나에 집중도 가능 — 선택은 여러분의 몫입니다. 각 트랙은 독립적인 학습 경험으로 설계되었습니다.',
'con.ra.title':'의료기기',
'con.ra.sub':'EBD 마스터 클래스 · 인더스트리 심포지엄',
'con.ra.desc':'최신 한국 에너지 기반 의료기기 기술에 관심 있는 미용 의사를 위한 트랙. 각 세션은 임상 근거, 시술 파라미터, 실제 기기를 사용한 라이브 환자 시연을 다룹니다.',
'con.rb.title':'미용성형',
'con.rb.sub':'한국 수술 표준 · 라이브 케이스 토론',
'con.rb.desc':'최신 한국 수술 기법을 원하는 성형외과의 및 미용성형 외과의를 위한 트랙. 시술 표준, 합병증 관리, SNUBH 교수와의 복잡 케이스 토론.',
'con.rc.title':'한국 프로토콜',
'con.rc.sub':'주사제 · 비수술 · 패널 Q&A',
'con.rc.desc':'비수술 시술에 초점을 맞춘 피부과 및 미용 의사를 위한 트랙. 모든 세션은 프로토콜 중심 — 한국 의사들이 실제로 어떻게 하는지, 베트남 환자와 진료 환경에 맞게 적용.',

// Full program
'con.sched.eyb':'전체 프로그램',
'con.sched.h2':'2026년 10월 17–18일 —<br><em>2일</em>',
'con.d1':'1일차 · 토요일, 10월 17일',
'con.d1.sub':'학술 세션 · 3개 병행 트랙 · 전시 · 갈라 디너',
'con.d2':'2일차 · 일요일, 10월 18일',
'con.d2.sub':'핸즈온 워크숍 · 라이브 수술 · CME 수료증',

// Congress KOL
'con.kol.eyb':'연사진',
'con.kol.h2':'학술대회 발표<br><em>한국 KOL</em>',

// Congress Policy
'con.policy.title':'참석 정책',
'con.policy.desc':'KSAPS 학술대회는 베트남 의료 전문가 전원 무료 — KHIDI 지원. 좌석 한정, KBIT 조직위원회 심사.',
'con.policy.p1':'신청 후 3~5 영업일 이내 확인',
'con.policy.p2':'갈라 디너 별도 심사 — 전문의 및 콤보 등록자 우선',
'con.policy.p3':'참석 불가 시 사전에 이메일 — secretary@kbitassociation.com',
'con.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향',
'con.cta.title':'KSAPS 학술대회 2026 참가',
'con.cta.desc':'10월 17일 · 108 중앙군사병원<br>하노이, 베트남<br>무료 참가 · 좌석 한정 · 심사 기반',
'con.cta.btn':'지금 등록 — 무료 →',
'con.cta.also':'다음 날 참가하시나요?',
'con.cta.also2':'KAT 베트남 10월 4일 등록 →',

// ===== KAT PAGE =====
'kat.tag':'KAT · K-Beauty Advanced Skills Training',
'kat.subtitle':'— 시리즈 중 가장 실용적인 교육의 날. 강연 없음. 순수 한국 기술을 베트남 의사에게 직접 전수 — 라이브 수술, 라이브 기기 시연, 1:5 라이브 관찰 및 Q&A.',
'kat.meta.date':'2026년 10월 4일 ',
'kat.meta.venue':'호치민시',
'kat.meta.type':'독립 행사',
'kat.meta.surgery':'라이브 수술 4건',
'kat.btn.register':'지금 등록 — 무료',
'kat.btn.schedule':'일정 보기 ↓',
'kat.glance':'한눈에 보기',
'kat.stat1':'의사',
'kat.stat2':'병행 트랙',
'kat.stat3':'라이브 수술 건수',
'kat.stat4':'KOL 대 의사',
'kat.included':'포함 내용',
'kat.inc1':'Room A: RF, HIFU, 피코 레이저 라이브 시연',
'kat.inc2':'보톡스 & 필러 핸즈온 (한국 KOL 직접 지도)',
'kat.inc3':'Room B: 라이브 비성형술, 안검성형, SVF',
'kat.inc4':'KAT 2026 수료증 — KSAPS + KBIT',
'kat.inc5':'KAT 2026 수료증',
'kat.what.eyb':'KAT의 차별점',
'kat.what.h2':'이론이 아닌, <em style="color:#F0C060">실습.</em>',
'kat.what.lead':'KAT 베트남 2026은 전날의 학술대회와 의도적으로 다릅니다. 학술대회가 3개 트랙에서 학문적 폭을 제공한다면, KAT은 한 방향으로 깊이 들어갑니다: 듣기만 한 것이 아니라 직접 해본 경험을 가지고 떠나는 것.',
'kat.wc1.title':'실시간 라이브 수술',
'kat.wc1.desc':'Room B에서 OR에서 직접 4건의 라이브 성형수술을 방송합니다. 각 건에는 수술 중인 한국 외과의의 단계별 해설과 청중의 실시간 Q&A가 포함됩니다. 녹화가 아닙니다 — 실제로 일어나는 것을 보는 것입니다.',
'kat.wc2.title':'한국 KOL 직접 지도 핸즈온',
'kat.wc2.desc':'Room A에서 종일 소그룹 핸즈온 세션 운영 — 베트남 의사 5명당 한국 KOL 1명. 각 그룹은 RF/HIFU 기기의 직접 파라미터 지도와 모델에 대한 보톡스 및 필러 주사 실습을 받습니다. 시범이 아닌 실제 실습입니다.',
'kat.wc3.title':'2일 여정의 2일차',
'kat.wc3.desc':'KAT 베트남은 KSAPS 학술대회(10월 17–18일)의 직접적인 후속 프로그램으로 설계되었습니다. 양쪽 모두 참석하면 베트남에서 가능한 가장 집중적인 한국 미용의학 교육 이틀을 경험합니다 — 각 행사별 별도 수료증.',

// ===== REGISTER PAGE (unified) =====
'reg.eyebrow':'K-Beauty MEETS 2026 · 등록',
'reg.sub':'하나의 양식. 하나, 둘, 또는 세 개 행사를 선택하세요. 정보를 한 번만 입력하면 — KBIT이 신청을 검토하고 확인된 각 행사에 대해 별도의 QR 티켓을 발급합니다.',
'reg.step1':'행사 선택',
'reg.step2':'상세정보',
'reg.step3':'관심 분야',
'reg.step4':'확인',
'reg.ev.title':'어떤 행사에 참석하시겠습니까?',
'reg.ev.sub':'하나, 둘, 또는 세 개를 선택하세요. 정보를 한 번만 입력하면 — KBIT이 검토 후 확인된 각 행사에 대해 별도의 QR 티켓을 보내드립니다.',
'reg.next':'상세정보 입력으로 →',
'reg.personal':'개인 정보',
'reg.fname':'이름 (성명) <span class="req">*</span>',
'reg.phone':'전화번호 <span class="req">*</span>',
'reg.email':'이메일 주소 <span class="req">*</span>',
'reg.cme':'CME 번호 / 의사면허',
'reg.hospital':'병원 / 클리닉 이름 <span class="req">*</span>',
'reg.city':'도시 <span class="req">*</span>',
'reg.specialty':'전공 <span class="req">*</span>',
'reg.experience':'경력 <span class="req">*</span>',
'reg.topics':'관심 분야',
'reg.goals':'K-Beauty MEETS에서 얻고 싶은 것은?',
'reg.policy.title':'참석 정책 — 제출 전 반드시 읽어주세요',
'reg.policy.p1':'무료 참가 — 행사당 좌석 한정. 등록이 참석을 보장하지 않습니다. <strong>등록 마감: 2026년 9월 26일.</strong>',
'reg.policy.p2':'확인 이메일은 3~5 영업일 이내 발송됩니다.',
'reg.policy.p3':'참석 불가 시 사전에 secretary@kbitassociation.com으로 이메일을 보내주세요.',
'reg.policy.p4':'사전 통보 없는 불참은 향후 행사 우선순위에 영향을 미칩니다.',
'reg.agree':'참석 정책을 읽었으며 동의합니다. 참석이 불가능한 경우 조직위원회에 통보할 것을 약속합니다.',
'reg.submit':'신청서 제출 →',
'reg.qr.title':'1개 양식 · 최대 3개 QR 티켓',
'reg.qr.sub':'KBIT이 확인된 각 행사에 대해 별도의 QR 티켓을 발급합니다. 당일 QR을 지참하여 체크인하세요.',
'reg.selected':'선택한 행사',
'reg.side.included':'포함 내용',
'reg.side.questions':'문의',
'reg.success.title':'등록이 완료되었습니다!',
'reg.success.code':'등록 코드:',
'reg.success.msg':'신청서를 검토하고 3~5 영업일 이내에 확인 이메일을 보내드리겠습니다.<br>체크인을 위해 등록 코드를 저장해 주세요.',
'reg.success.back':'홈페이지로 돌아가기',

// ===== SPEAKERS PAGE =====
'spk.eyb':'K-Beauty MEETS 2026',
'spk.title':'베트남에 오는<br>한국 KOL 15인',
'spk.desc':'한국에서 가장 존경받는 미용 외과의와 의사들 — KSAPS와 SNUBH 소속 — 수십 년의 임상 경험을 호치민시의 세 개 행사에 직접 가져옵니다.',
'spk.filter.all':'전체 KOL',
'spk.filter.summit':'서밋',
'spk.filter.congress':'학술대회',
'spk.filter.kat':'KAT',
'spk.filter.surgery':'수술',
'spk.filter.devices':'기기',
'spk.specialty':'전공 & 주제',
'spk.events':'참가 행사',
'spk.more':'추가 KOL 7명',
'spk.more.sub':'핸즈온 트랙 강사',
'spk.coverage':'담당 분야',

// VSAPS section
'spk.vsaps.eyb':'베트남 파트너',
'spk.vsaps.h2':'VSAPS —<br>베트남 미용성형<br>외과의로의 <em>관문</em>',
'spk.vsaps.p1':'베트남미용성형외과학회(VSAPS)는 K-Beauty MEETS 2026의 공식 베트남 파트너입니다. 2007년에 설립되어 베트남 보건부의 인정을 받은 VSAPS는 베트남 미용성형의 중심 조직입니다.',
'spk.vsaps.p2':'KSAPS-VSAPS 파트너십 MOU는 2026년 4월 서울에서 열린 APS Korea 2026에서 체결되었습니다 — VSAPS 회장 Dr. Lê Hành과 23명의 VSAPS 이사회 멤버가 참석했습니다. 이를 통해 K-Beauty MEETS는 베트남 전체 미용성형 커뮤니티에 직접 접근할 수 있게 되었습니다.',
'spk.vsaps.s1':'베트남 미용성형 외과의의',
'spk.vsaps.s1b':'이상이 VSAPS 회원',
'spk.vsaps.s2':'활동 회원 의사 — 모두 임상 의사결정자',
'spk.vsaps.s3':'설립 · 베트남 보건부 인정',
'spk.vsaps.s4':'연례 학술대회 10회 달성 — 2026',

// CTA
'spk.cta.eyb':'K-Beauty MEETS 2026',
'spk.cta.title':'호치민시에서 이 의사들을 만나세요',
'spk.cta.desc':'15명의 한국 KOL이 세 개 행사에서 발표, 시연, 교육합니다 — 베트남 의료 전문가 전원 무료.',
'spk.cta.summit':'서밋 등록',
'spk.cta.congress':'학술대회 등록',
'spk.cta.kat':'KAT 등록',

// ===== BUSINESS MEETING PAGE =====
'biz.eyb':'비즈니스 미팅 프로그램',
'biz.h2':'베트남 최고의<br><em>미용 클리닉</em>에 대한 체계적 접근',
'biz.lead':'비즈니스 미팅 프로그램은 한국 의료기기 기업에게 K-Beauty MEETS 행사에 참석하는 베트남 병원장, 클리닉 원장, 구매 관리자와의 직접 예약 1:1 미팅을 제공합니다. KBIT이 매칭과 일정을 조율합니다.',
'biz.wc1.title':'맞춤형 1:1 매칭',
'biz.wc1.desc':'KBIT이 귀사의 기업 프로필과 미팅 목표를 검토한 후, 사전 검증된 베트남 바이어 — 행사에 참석하는 병원장, 클리닉 원장, 의료장비 구매 관리자 — 와 매칭합니다.',
'biz.wc2.title':'사전 확인 & 예약',
'biz.wc2.desc':'각 행사 점심 및 커피 브레이크 시간 중 30분 전용 세션. 모든 미팅 양측 사전 확인. 전담 통역 제공. 구매 의사가 있는 경우 현장 LOI 체결 지원.',
'biz.wc3.title':'3개 행사 · 2개 도시',
'biz.wc3.desc':'1개, 2개, 또는 3개 행사 모두 등록 가능. 각 행사는 베트남 미용의학 시장의 다른 세그먼트에 접근 — 서밋과 KAT의 호치민시 전문의, 학술대회의 하노이 및 전국 참가자.',
'biz.side.title':'3개 행사 · 2개 도시',
'biz.side.summit':'서밋 + KAT',
'biz.side.congress':'학술대회',
'biz.side.reach':'총 접근 규모',
'biz.side.reachval':'의료 전문가 1,200명 이상',
'biz.side.reachsub':'전체 3개 행사 합산',
'biz.side.provides':'KBIT 제공 서비스',
'biz.side.prov1':'바이어 매칭 & 사전 일정',
'biz.side.prov2':'한국어 ↔ 베트남어 통역',
'biz.side.prov3':'행사장 내 미팅룸 / 공간',
'biz.side.prov4':'LOI 문서 지원',
'biz.side.prov5':'행사 후 후속 조치 지원',
'biz.side.prov6':'수출 상담 보고서',
'biz.side.questions':'문의',
};

window.KO_TEXT={
"Summit":"서밋",
"Business":"비즈니스",
"Register":"등록",
"KSAPS Summit":"KSAPS 서밋",
"KSAPS Congress":"KSAPS 학술대회",
"KSAPS Congress 2026":"KSAPS 학술대회 2026",
"KAT Vietnam":"KAT 베트남",
"KAT Vietnam 2025":"KAT 베트남 2025",
"KAT Vietnam 2026":"KAT 베트남 2026",
"KAT China 2026":"KAT 중국 2026",
"Business Meeting Registration — K-Beauty MEETS 2026":"비즈니스 미팅 등록 — K-Beauty MEETS 2026",
"Register — K-Beauty MEETS 2026":"등록 — K-Beauty MEETS 2026",
"Speakers — K-Beauty MEETS 2026":"연사진 — K-Beauty MEETS 2026",
"KAT Vietnam 2026 — K-Beauty Advanced Skills Training · K-Beauty MEETS":"KAT 베트남 2026 — K-Beauty Advanced Skills Training · K-Beauty MEETS",
"Korea Meets VSAPS · KSAPS Congress 2026":"Korea Meets VSAPS · KSAPS 학술대회 2026",
"Delegates":"참가자",
"Parallel rooms all day":"종일 3개 병행 트랙",
"Korean KOL presenting":"발표 한국 KOL",
"Exhibition booths":"전시 부스",
"Oct 17–18":"10월 17–18일",
"Oct 3":"10월 3일",
"Oct 4":"10월 4일",
"Thread":"실",
"Filler":"필러",
"Bio-filler":"바이오필러",
"Cooling":"쿨링",
"Confirmed":"확정",
"Sutures · Materials":"봉합사 · 소재",
"Hironic DOUBLO":"하이로닉 DOUBLO",
"Wontech Oligio":"원텍 Oligio",
"Neodoctors JAMBER":"네오닥터 JAMBER",
"Aestheform QTFILL":"에스테팜 QTFILL",
"Roselab BIOSTER":"로즈랩 BIOSTER",
"Ho Chi Minh City & Hanoi, Vietnam · October 2026":"호치민시 & 하노이, 베트남 · 2026년 10월",
"Where Korean excellence meets Asia":"한국의 우수한 의료기술이 아시아를 만나다",
"K-Standard Protocol":"K-스탠다드 프로토콜",
"Q&A Panel":"Q&A 패널",
"Congress · CME":"학술대회 · CME",
"Hands-on":"핸즈온",
"Live Surgery":"라이브 수술",
"What is K-Beauty MEETS?":"K-Beauty MEETS란?",
"The standard has changed.":"기준이 바뀌었습니다.",
"Are you ready?":"준비되셨습니까?",
"Korean aesthetic medicine leads the world. K-Beauty MEETS gives Vietnamese doctors direct access to the people, protocols, and devices driving that standard — not through textbooks, but through hands-on experience in their own city.":"한국 미용의학은 세계를 선도합니다. K-Beauty MEETS는 베트남 의사들에게 그 기준을 이끄는 전문가, 프로토콜, 기기에 직접 접근할 수 있는 기회를 제공합니다 — 교과서가 아닌 자신의 도시에서의 실습 경험을 통해.",
"15 Key Opinion Leaders from KSAPS and SNUBH — Korea's most respected aesthetic societies. Not recorded lectures. The actual surgeons and doctors, in the room with you, operating and answering your questions in real time.":"KSAPS와 SNUBH 소속 15명의 핵심 오피니언 리더(KOL) — 한국에서 가장 존경받는 미용성형 학회입니다. 녹화된 강의가 아니라 실제 외과의와 의사들이 같은 공간에서 수술하고 실시간으로 질문에 답합니다.",
"Live device demos. Live surgery broadcast. Small-group hands-on at 1:5. Every session is designed around clinical application — protocols you can use in your clinic immediately, adapted for Vietnamese patients.":"라이브 기기 시연. 라이브 수술 방송. 1:5 소그룹 핸즈온. 모든 세션은 임상 적용 중심으로 설계되어 베트남 환자에 맞게 클리닉에서 즉시 사용할 수 있는 프로토콜을 제공합니다.",
"Funded by KHIDI — the Korean Health Industry Development Institute under the Ministry of Health & Welfare. All events are free to attend for Vietnamese medical professionals. Limited seats, application-based.":"보건복지부 산하 한국보건산업진흥원(KHIDI) 지원. 모든 행사는 베트남 의료 전문가에게 무료이며, 좌석 한정 및 심사 기반 등록입니다.",
"Korea Meets VSAPS · HCMC":"Korea Meets VSAPS · 호치민시",
"Korea Meets VSAPS · Hanoi":"Korea Meets VSAPS · 하노이",
"KAT · HCMC":"KAT · 호치민시",
"\"Korean Beauty — Latest Advances in Aesthetic Surgery & Medical Devices\"":"\"Korean Beauty — 미용성형 및 의료기기 최신 동향\"",
"\"Your Hands. Korean Technique.\"":"\"당신의 손. 한국의 기술.\"",
"\"Korean Beauty — Cutting-edge Aesthetic Surgery & Medical Technology\"":"\"Korean Beauty — 최첨단 미용성형 및 의료 기술\"",
"October 3, 2026 · Kangnam Aesthetic Hospital":"2026년 10월 3일 · 강남미용성형병원",
"October 4, 2026 · Ho Chi Minh City":"2026년 10월 4일 · 호치민시",
"October 17–18, 2026 · 108 Military Central Hospital, Hanoi":"2026년 10월 17–18일 · 108 중앙군사병원, 하노이",
"100 doctors · 1 day · HCMC":"의사 100명 · 1일 · 호치민시",
"Press Conference · Lecture · Live Device Demo · Live Surgery":"기자회견 · 강연 · 라이브 기기 시연 · 라이브 수술",
"An intensive 2-day workshop at Kangnam Aesthetic Hospital — Vietnam's premier private aesthetic facility. Day 1: lectures and live device demos. Day 2: press conference, live surgery broadcast, and hands-on Botox/filler/thread training.":"강남미용성형병원에서 진행되는 집중 워크숍입니다 — 베트남 최고의 민간 미용성형 시설. 강연, 라이브 기기 시연, 기자회견, 라이브 수술 방송, 보톡스/필러/실리프팅 핸즈온 교육으로 구성됩니다.",
"Independent event Day 2":"독립 행사 2일차",
"Live Device Demo · Botox & Filler Live · Live Plastic Surgery":"라이브 기기 시연 · 보톡스 & 필러 라이브 · 라이브 성형수술",
"Live Plastic Surgery":"라이브 성형수술",
"KAT 2026 Certificate":"KAT 2026 수료증",
"K-Beauty Advanced Skills Training — co-hosted . Pure skills transfer: live surgery from the OR, device demos, and direct hands-on Botox and filler practice with Korean KOL instruction.":"K-Beauty Advanced Skills Training — 순수 기술 전수 프로그램입니다. 수술실 라이브 수술, 기기 시연, 한국 KOL 지도 아래 보톡스 및 필러 직접 실습으로 구성됩니다.",
"~1,000 delegates · 2 days · Hanoi":"약 1,000명 참가 · 2일 · 하노이",
"Academic sessions + 3 Parallel rooms":"학술 세션 + 3개 병행 트랙",
"10 Korean company exhibition":"한국 기업 10개사 전시",
"Hands-on Workshop + Gala Dinner":"핸즈온 워크숍 + 갈라 디너",
"Vietnam's largest Korea–Vietnam aesthetic medical congress. Two full days at 108 Military Central Hospital in Hanoi — academic sessions, parallel rooms, 10-company exhibition, live surgery, hands-on training, and VIP Gala Dinner.":"베트남 최대 한·베 미용의학 학술대회입니다. 하노이 108 중앙군사병원에서 학술 세션, 병행 트랙, 10개사 전시, 라이브 수술, 핸즈온 교육, VIP 갈라 디너가 진행됩니다.",
"KAT — K-Beauty Advanced Skills Training — brings Korean KOL directly to local doctors for real hands-on skills transfer. Each year, a new Asian city. Each edition, a deeper network of Korean-trained aesthetic professionals.":"KAT — K-Beauty Advanced Skills Training — 한국 KOL이 현지 의사들에게 직접 실습 기술을 전수합니다. 매년 새로운 아시아 도시에서 진행되며, 회차마다 한국식 교육을 받은 미용 전문가 네트워크가 깊어집니다.",
"KAT 2025 trained 350 doctors, generated $1.34M in export consultations, and was recognized by Vietnam's Ministry of Health as a model of medical cooperation. KAT Vietnam 2026 builds on that foundation.":"KAT 2025는 의사 350명을 교육하고 134만 달러의 수출 상담을 달성했으며, 베트남 보건부로부터 의료 협력의 모범 사례로 인정받았습니다. KAT 베트남 2026은 그 기반 위에 구축됩니다.",
"Le Van Thinh Hospital, HCMC":"Le Van Thinh 병원, 호치민시",
"China · Details to be announced":"중국 · 상세 내용 추후 공개",
"October 4 · Ho Chi Minh City":"10월 4일 · 호치민시",
"KAT 2025 was recognized by Vietnam's Ministry of Health as a model case of Korea–Vietnam medical cooperation. National media covered the event across multiple outlets.":"KAT 2025는 베트남 보건부로부터 한·베 의료 협력의 모범 사례로 인정받았습니다. 국내 주요 언론이 다수 보도했습니다.",
"Vietnam Ministry of Health":"베트남 보건부",
"Exhibition booths and Industry Symposia at KSAPS Congress Hanoi — direct access for 1,000+ Vietnamese medical professionals to Korea's latest aesthetic technology.":"KSAPS 학술대회 하노이의 전시 부스 및 인더스트리 심포지엄을 통해 1,000명 이상의 베트남 의료 전문가에게 한국 최신 미용 기술을 직접 소개합니다.",
"All K-Beauty MEETS events are fully free for Vietnamese medical professionals. Supported by KHIDI — the Korean Health Industry Development Institute — and organized by KSAPS, SNUBH, VSAPS, and KBIT.":"모든 K-Beauty MEETS 행사는 베트남 의료 전문가에게 완전 무료입니다. KHIDI(한국보건산업진흥원) 지원, KSAPS, SNUBH, VSAPS, KBIT 공동 주최.",
"Seats are limited. Applications reviewed by KBIT within 3–5 business days. Priority to specialist physicians (aesthetic surgery, dermatology, plastic surgery).":"좌석이 한정되어 있습니다. KBIT에서 3~5 영업일 이내에 심사합니다. 전문의(미용성형, 피부과, 성형외과)를 우선합니다.",
"If you cannot attend, email secretary@kbitassociation.com in advance. Unannounced no-shows are recorded and affect priority at future KSAPS and KAT events.":"참석이 불가능한 경우 사전에 secretary@kbitassociation.com으로 이메일을 보내주세요. 사전 통보 없는 불참은 향후 KSAPS 및 KAT 행사 우선순위에 영향을 미칩니다.",
"KAT Vietnam 2026 · Oct 4 · HCMC":"KAT 베트남 2026 · 10월 4일 · 호치민시",
"Register for Summit":"서밋 등록",
"Register for KAT":"KAT 등록",
"Register for Congress":"학술대회 등록",
"An intensive 2-day workshop at Kangnam Aesthetic Hospital HCMC — Press Conference · Scientific Lectures · Live Device Demo · Live Surgery — all in one intensive day. Lectures, live surgery broadcast from the OR, and small-group hands-on at a 1:5 KOL-to-doctor ratio.":"강남미용성형병원 호치민시에서 진행되는 집중 워크숍입니다 — 기자회견, 학술 강연, 라이브 기기 시연, 라이브 수술을 하루에 경험합니다. 강연, 수술실 라이브 방송, 1:5 KOL 대 의사 비율의 소그룹 핸즈온으로 구성됩니다.",
"Lectures by KSAPS & SNUBH professors":"KSAPS & SNUBH 교수 강연",
"Live device demo — 6 Korean companies":"라이브 기기 시연 — 한국 기업 6개사",
"Live OR surgery broadcast (Day 1)":"라이브 OR 수술 방송 (1일차)",
"K-Protocol Certificate":"K-프로토콜 수료증",
"One focused day — press conference in the morning, scientific lectures, live device demonstrations in the afternoon, and a live rhinoplasty surgery broadcast from the OR to close.":"하루 집중 프로그램 — 오전 기자회견과 학술 강연, 오후 라이브 기기 시연, 마지막 라이브 비성형술 수술 방송으로 구성됩니다.",
"Joint statement by KSAPS · VSAPS · KBIT representatives":"KSAPS · VSAPS · KBIT 대표 공동 성명",
"Domestic and international press invited · Photo opportunity":"국내외 언론 초청 · 포토 타임",
"Lecture 1 — HIFU & RF Combination Lifting Protocol":"강연 1 — HIFU & RF 복합 리프팅 프로토콜",
"Lecture 2 — Advanced Rhinoplasty: Korean Standards 2026":"강연 2 — 고급 비성형술: 한국 표준 2026",
"Lecture 3 — Thread Lifting & High-viscosity Filler Protocol":"강연 3 — 실리프팅 & 고점도 필러 프로토콜",
"Lecture 4 — Regenerative Bio-filler & SVF Clinical Application":"강연 4 — 재생 바이오필러 & SVF 임상 적용",
"Prof. Heo Chan-yeong · KSAPS / SNUBH":"허찬영 교수 · KSAPS / SNUBH",
"Prof. Kim Baek-gyu · SNUBH":"김백규 교수 · SNUBH",
"Dr. Park Young-jin · KSAPS":"박영진 원장 · KSAPS",
"Prof. Park Eun-su · SNUBH":"박은수 교수 · SNUBH",
"Buffet lunch · Free networking between Korean KOL and Vietnamese doctors":"뷔페 점심 · 한국 KOL과 베트남 의사 간 자유 네트워킹",
"Each company presents their flagship device with a live demonstration on a patient or model — parameter guidance, clinical protocol, and Q&A included.":"각 기업이 환자 또는 모델에게 플래그십 기기를 라이브 시연합니다 — 파라미터 가이드, 임상 프로토콜, Q&A 포함.",
"Company 1 — Device Demo":"기업 1 — 기기 시연",
"Company 2 — Device Demo":"기업 2 — 기기 시연",
"Company 3 — Device Demo":"기업 3 — 기기 시연",
"Korean-standard rhinoplasty performed by KSAPS KOL":"KSAPS KOL이 시행하는 한국 표준 비성형술",
"Live UHD broadcast from OR to main hall":"수술실에서 메인홀로 라이브 UHD 방송",
"Step-by-step commentary throughout · Real-time Q&A with surgeon":"전 과정 단계별 해설 · 집도의와 실시간 Q&A",
"Patient pre-screened and consented · Vietnamese anaesthesia team on standby":"환자 사전 검사 및 동의 완료 · 베트남 마취팀 대기",
"Closing remarks · Certificate presentation":"폐회사 · 수료증 수여",
"Invitation to KSAPS Congress — October 17–18, Hanoi":"KSAPS 학술대회 초대 — 10월 17–18일, 하노이",
"Two premier private aesthetic":"호치민시 최고의 민간 미용",
"hospitals in HCMC":"성형 병원 2곳",
"Both venues were selected for their world-class OR facilities, broadcast infrastructure, and track record in Korea-Vietnam medical collaboration. Not conference hotels — real working hospitals where real patients are treated.":"두 곳 모두 세계적 수준의 수술실 시설, 방송 인프라, 한·베 의료 협력 실적을 기반으로 선정되었습니다. 컨퍼런스 호텔이 아닌 실제 환자를 치료하는 병원입니다.",
"Kangnam Aesthetic Hospital":"강남미용성형병원",
"One of HCMC's largest private aesthetic hospitals":"호치민시 최대 민간 미용성형 병원 중 하나",
"Full OR suite with HDMI/SDI live-feed broadcast system":"HDMI/SDI 라이브 방송 시스템을 갖춘 수술실",
"Experienced team in Korea-Vietnam procedures":"한·베 시술 경험이 풍부한 팀",
"Kim Baek-gyu · Park Young-jin · Park Eun-su — Oligio · V-RO · JAMBER · QTFILL · BIOSTER":"김백규 · 박영진 · 박은수 — Oligio · V-RO · JAMBER · QTFILL · BIOSTER",
"Lecture":"강연",
"Demo":"시연",
"Live Surgery — Blepharoplasty":"라이브 수술 — 안검성형",
"Advanced double eyelid · Real-time Q&A":"고급 쌍꺼풀 수술 · 실시간 Q&A",
"Leading aesthetic hospital system in HCMC":"호치민시 선도적 미용성형 병원 시스템",
"Configured for hands-on training stations":"핸즈온 교육 스테이션 설치",
"Broadens the KOL network reach to second venue":"KOL 네트워크를 제2 개최지로 확대",
"Track A / B / C · 1 KOL per 5 doctors":"Track A / B / C · 의사 5명당 KOL 1명",
"Certificate Ceremony":"수료식",
"K-Protocol Certified · KOL Network registration":"K-프로토콜 인증 · KOL 네트워크 등록",
"Every device featured at KSAPS Summit is demonstrated live by the KOL who helped develop its clinical protocol — not a company rep, not a trainer. The actual Korean doctor who uses it in their practice, showing you exactly how.":"KSAPS 서밋에서 선보이는 모든 기기는 임상 프로토콜 개발에 참여한 KOL이 직접 라이브 시연합니다 — 기업 담당자나 트레이너가 아닌 실제 진료에서 사용하는 한국 의사가 보여줍니다.",
"Focused ultrasound for deep tissue lifting at SMAS layer. Featured in K-Layered Lifting protocol combined with RF for synergistic facial contouring.":"SMAS 층의 심부 조직 리프팅을 위한 집속초음파. RF와 결합한 K-Layered Lifting 프로토콜에 활용됩니다.",
"Wontech · Innovative Medical Device":"원텍 · 혁신 의료기기",
"High-viscosity hyaluronic acid filler. VMD complete for immediate Vietnam market use. Demonstrated live with midface, lip, and nasolabial fold injection protocols.":"고점도 히알루론산 필러. 베트남 시장 즉시 사용을 위한 VMD 완료. 중안면, 입술, 팔자주름 주입 프로토콜을 라이브로 시연합니다.",
"Next-generation tissue regeneration bio-filler for autologous collagen activation. Clinical trials in progress. KGMP Vietnam pathway under Korea-Vietnam cooperation.":"자가 콜라겐 활성화를 위한 차세대 조직 재생 바이오필러. 임상시험 진행 중이며 한·베 협력을 통한 KGMP 베트남 경로를 추진합니다.",
"Clinical trials · KGMP · Vietnam pathway":"임상시험 · KGMP · 베트남 경로",
"Participation confirmed. Korea's leading dental and aesthetic pharmaceutical company. Product details and session assignment to be announced before August.":"참가 확정. 한국의 대표 치과 및 미용 제약 기업. 제품 세부 정보와 세션 배정은 8월 전 공지 예정입니다.",
"Details coming soon":"상세 내용 추후 공개",
"These are not guest speakers — they are the people who wrote the clinical protocols being demonstrated. The 1:5 hands-on on Day 2 means direct, personal time with each of them.":"이들은 단순 초청 연사가 아니라 시연되는 임상 프로토콜을 직접 만든 전문가입니다. 2일차 1:5 핸즈온에서 각 KOL과 직접 시간을 가질 수 있습니다.",
"The hands-on summit format was tested and refined at KAT 2025. Vietnam's Ministry of Health called it a model of medical cooperation. KAT 2025 data shows what happens when Korean KOL go hands-on directly with Vietnamese doctors.":"핸즈온 서밋 형식은 KAT 2025에서 검증되고 개선되었습니다. 베트남 보건부는 이를 의료 협력의 모범 사례라고 평가했습니다. KAT 2025 데이터는 한국 KOL이 베트남 의사와 직접 핸즈온할 때의 성과를 보여줍니다.",
"Export consultations in one day":"하루 수출 상담 실적",
"Vietnam Ministry of Health recognition":"베트남 보건부 인정",
"Expanded to Summit + Congress + KAT":"서밋 + 학술대회 + KAT으로 확대",
"— highly selective. Both days can be applied for.":"— 엄격 심사. 양일 모두 신청 가능.",
"Confirmation in":"확인까지",
"after application.":"신청 후 소요.",
"Cannot attend? Email":"참석이 어렵다면 이메일로",
"in advance.":"사전에 알려주세요.",
"future event priority":"향후 행사 우선순위",
"Attending Congress Oct 17–18 in Hanoi?":"10월 17–18일 하노이 학술대회도 참가하시나요?",
"— the most practical training day of the series. No lectures. Pure Korean techniques transferred directly to Vietnamese doctors — through live surgery, live device demos, and live observation and Q&A at 1:5.":"— 시리즈 중 가장 실용적인 교육의 날입니다. 강연이 아닌 순수 한국 기술을 베트남 의사에게 직접 전수합니다 — 라이브 수술, 라이브 기기 시연, 1:5 라이브 관찰 및 Q&A.",
"Independent event":"독립 행사",
"Room A: RF, HIFU, Pico Laser live demos":"Room A: RF, HIFU, 피코 레이저 라이브 시연",
"Botox & filler hands-on (with direct Korean KOL guidance)":"보톡스 & 필러 핸즈온 (한국 KOL 직접 지도)",
"Room B: Live Rhinoplasty, Blepharoplasty, SVF":"Room B: 라이브 비성형술, 안검성형, SVF",
"KAT 2026 Certificate — KSAPS + KBIT":"KAT 2026 수료증 — KSAPS + KBIT",
"KAT Vietnam 2026 is deliberately different from the Congress happening the day before. Where Congress delivers academic breadth across three rooms, KAT goes deep in one direction: you leave having done it — not just having heard about it.":"KAT 베트남 2026은 전날 학술대회와 의도적으로 다릅니다. 학술대회가 3개 트랙에서 학문적 폭을 제공한다면, KAT은 한 방향으로 깊이 들어갑니다. 듣기만 하는 것이 아니라 직접 해본 경험을 가지고 떠납니다.",
"Room B broadcasts 4 live plastic surgery cases directly from the OR. Each case has step-by-step commentary from the operating Korean surgeon, with real-time Q&A from the audience. You're not watching a recording — you're watching it happen.":"Room B에서는 수술실에서 직접 4건의 라이브 성형수술을 방송합니다. 각 케이스에는 한국 집도의의 단계별 해설과 청중의 실시간 Q&A가 포함됩니다. 녹화가 아닌 실제 수술을 보게 됩니다.",
"Rhinoplasty · Blepharoplasty · SVF & Fat Grafting · Mini Facelift — all with OR live broadcast":"비성형술 · 안검성형 · SVF & 지방이식 · 미니 페이스리프트 — 모두 수술실 라이브 방송",
"Room A runs small-group hands-on sessions throughout the day — one Korean KOL for every five Vietnamese doctors. Each group gets direct parameter guidance for RF/HIFU devices and hands-on Botox and filler injection on models. Not demonstration — actual practice.":"Room A에서는 종일 소그룹 핸즈온 세션이 운영됩니다 — 베트남 의사 5명당 한국 KOL 1명. 각 그룹은 RF/HIFU 기기 파라미터 지도와 모델 대상 보톡스 및 필러 주입 실습을 받습니다. 시연이 아닌 실제 실습입니다.",
"The same 1:5 format used in KAT 2025 — recognized by Vietnam's Ministry of Health as a model of Korea-Vietnam medical cooperation":"KAT 2025에서 사용된 동일한 1:5 형식 — 베트남 보건부가 한·베 의료 협력의 모범 사례로 인정",
"KAT Vietnam is designed as the direct follow-on to KSAPS Congress (Oct 17–18). Doctors who attend both leave with two days of the most concentrated Korean aesthetic education available in Vietnam — separate certificates for each event.":"KAT 베트남은 KSAPS 학술대회(10월 17–18일)의 직접 후속 프로그램으로 설계되었습니다. 두 행사 모두 참석하면 베트남에서 가능한 가장 집중적인 한국 미용의학 교육 이틀을 경험하며, 각 행사별 별도 수료증을 받습니다.",
"Congress + KAT combo registrants receive higher review priority and separate certificates for both events":"학술대회 + KAT 콤보 등록자는 심사 우선순위가 높으며 두 행사 각각의 수료증을 받습니다",
"Delegates choose one room or move freely between both. Room A is a procedure training room. Room B is a full OR suite with UHD cameras broadcasting to large screens. Both run all day with only a lunch break.":"참가자는 한 룸을 선택하거나 두 룸 사이를 자유롭게 이동할 수 있습니다. Room A는 시술 교육룸, Room B는 UHD 카메라가 대형 화면으로 송출되는 수술실입니다. 두 룸 모두 점심시간을 제외하고 종일 운영됩니다.",
"Room A — Live Demo & Hands-on":"Room A — 라이브 시연 & 핸즈온",
"Botox & Filler injection · 1:5 hands-on groups":"보톡스 & 필러 주입 · 1:5 핸즈온 그룹",
"Room B — Live Plastic Surgery":"Room B — 라이브 성형수술",
"Rhinoplasty · Blepharoplasty · SVF · Mini Facelift":"비성형술 · 안검성형 · SVF · 미니 페이스리프트",
"Both rooms run simultaneously 09:00–16:30. Morning and afternoon sessions in each room with coffee breaks in between.":"두 룸은 09:00–16:30 동시에 운영됩니다. 각 룸에서 오전/오후 세션이 진행되며 중간에 커피 브레이크가 있습니다.",
"Live device demonstrations followed by direct small-group live observation and Q&A. One Korean KOL guides every 5 Vietnamese doctors through each technique. Participants leave with real operational knowledge — not just product awareness.":"라이브 기기 시연 후 소그룹 라이브 관찰과 Q&A가 이어집니다. 한국 KOL 1명이 베트남 의사 5명에게 각 기술을 직접 지도합니다. 참가자는 단순 제품 인지가 아닌 실제 운영 지식을 얻게 됩니다.",
"Demo A1 — Energy Devices":"시연 A1 — 에너지 기기",
"Demo A2 — Laser + Botox & Filler Live":"시연 A2 — 레이저 + 보톡스 & 필러 라이브",
"Pico laser skin rejuvenation demo · Botox live injection: forehead, glabella, crow's feet · Skin booster protocol":"피코 레이저 피부 재생 시연 · 보톡스 라이브 주입: 이마, 미간, 눈가 · 스킨부스터 프로토콜",
"Demo A3 — Filler Live & Thread":"시연 A3 — 필러 라이브 & 실",
"Filler live injection: midface, nasolabial fold, lip augmentation · PCL thread lifting demo":"필러 라이브 주입: 중안면, 팔자주름, 입술 볼륨 · PCL 실리프팅 시연",
"Demo A4 — Combination + Body":"시연 A4 — 복합 시술 + 바디",
"Combined Laser + Filler + RF protocol · Cryolipolysis / EMSculpt · Room A wrap-up":"레이저 + 필러 + RF 복합 프로토콜 · 냉각지방분해 / EMSculpt · Room A 마무리",
"Four live surgery cases broadcast directly from the operating room. UHD cameras cover every detail. Each case begins with a patient and case presentation, then the surgery, with step-by-step commentary and audience Q&A throughout.":"수술실에서 직접 4건의 라이브 수술을 방송합니다. UHD 카메라가 세부 과정을 보여주며, 각 케이스는 환자 및 케이스 발표 후 수술, 단계별 해설, 청중 Q&A로 진행됩니다.",
"Live Surgery B1 — Rhinoplasty":"라이브 수술 B1 — 비성형술",
"Korean-standard rhinoplasty · OR live broadcast · Step-by-step + Q&A":"한국 표준 비성형술 · 수술실 라이브 방송 · 단계별 해설 + Q&A",
"Live Surgery B2 — Blepharoplasty":"라이브 수술 B2 — 안검성형",
"Advanced double eyelid · Korean incision design · Live Q&A":"고급 쌍꺼풀 수술 · 한국식 절개 디자인 · 라이브 Q&A",
"Lunch · Speaker debrief":"점심 · 연자 디브리프",
"Live Surgery B3 — SVF & Fat Grafting":"라이브 수술 B3 — SVF & 지방이식",
"SVF stem cell isolation · Fat grafting for facial rejuvenation · Clinical discussion":"SVF 줄기세포 분리 · 안면 회춘 지방이식 · 임상 토론",
"Live Surgery B4 — Mini Facelift / Revision":"라이브 수술 B4 — 미니 페이스리프트 / 재수술",
"Korean minimal-incision technique · Panel: Complications & prevention · Room B wrap-up":"한국식 최소절개 기법 · 패널: 합병증 및 예방 · Room B 마무리",
"KAT Vietnam 2026 Certificate · KAT 2027 announcement · Group photo":"KAT 베트남 2026 수료증 · KAT 2027 안내 · 단체 사진",
"KAT is not a one-time event. Each year, a new Asian city is added to the network — building a continent-wide community of Korean-trained aesthetic professionals and opening new markets for Korean medical technology.":"KAT은 일회성 행사가 아닙니다. 매년 새로운 아시아 도시가 네트워크에 추가되어 한국식 교육을 받은 미용 전문가 커뮤니티를 구축하고 한국 의료기술의 새 시장을 엽니다.",
"KAT 2025 Vietnam set the standard. KAT China 2026 expands the series. KAT Vietnam 2026 deepens the Vietnamese network. KAT 2027 continues the mission in a new city.":"KAT 베트남 2025가 기준을 세웠고, KAT 중국 2026이 시리즈를 확장합니다. KAT 베트남 2026은 베트남 네트워크를 더욱 깊게 하며, KAT 2027은 새로운 도시에서 미션을 이어갑니다.",
"Vietnam MoH recognition":"베트남 보건부 인정",
"Series expanding to new market":"새 시장으로 시리즈 확장",
"Kangnam Aesthetic Hospital area, HCMC · HCMC":"강남미용성형병원 일대, 호치민시",
"Independent event · Oct 4, 2026":"독립 행사 · 2026년 10월 4일",
"Next Asian city to be announced":"다음 아시아 도시 추후 공개",
"Growing the network":"네트워크 확장",
"Export consultations achieved in one day":"하루 수출 상담 실적",
"Distributors requested follow-up meetings":"유통업체 후속 미팅 요청",
"Hospitals requested formal partnership":"병원 공식 파트너십 요청",
"The first Korea–Vietnam KAT workshop at Le Van Thinh Hospital, HCMC — covered by HTV and national media. Vietnam's Ministry of Health recognized it as a model of bilateral medical cooperation focused on genuine skills transfer.":"Le Van Thinh 병원, 호치민시에서 열린 첫 한·베 KAT 워크숍은 HTV와 국내 언론에 보도되었습니다. 베트남 보건부는 진정한 기술 전수에 초점을 맞춘 양국 의료 협력의 모범 사례로 인정했습니다.",
"\"A model case of Korea-Vietnam medical cooperation — focused on genuine, practical skills transfer rather than product showcase.\"":"\"제품 쇼케이스가 아닌 진정성 있는 실전 기술 전수에 초점을 맞춘 한·베 의료 협력의 모범 사례.\"",
"— Vietnam Ministry of Health official evaluation, 2025":"— 베트남 보건부 공식 평가, 2025",
"KAT Vietnam 2026 is free for all qualified Vietnamese medical professionals. Supported by KHIDI and organized by KSAPS, SNUBH, VSAPS, and KBIT.":"KAT 베트남 2026은 자격을 갖춘 베트남 의료 전문가에게 무료입니다. KHIDI 지원, KSAPS, SNUBH, VSAPS, KBIT 주관.",
"— reviewed by KBIT. Priority to specialist physicians and Congress combo registrants.":"— KBIT 심사. 전문의 및 학술대회 콤보 등록자 우선.",
"priority at KAT 2027":"KAT 2027 우선순위",
"Independent event. 4 live OR surgeries. Botox & filler at 1:5.":"독립 행사. 라이브 OR 수술 4건. 1:5 보톡스 & 필러.",
"October 4 at Ho Chi Minh City.":"10월 4일 호치민시.",
"coming to Vietnam":"베트남에 오는",
"Korea's most respected aesthetic surgeons and doctors — from KSAPS and SNUBH — bringing decades of clinical expertise directly to Ho Chi Minh City for three events across two months.":"한국에서 가장 존경받는 미용 외과의와 의사들이 — KSAPS와 SNUBH 소속 — 수십 년의 임상 경험을 호치민시의 세 행사에 직접 가져옵니다.",
"Next President, Korean Society of Aesthetic Plastic Surgery":"대한미용성형외과학회 차기 회장",
"Head, Dept. of Plastic Surgery · SNUBH":"성형외과 과장 · SNUBH",
"Rhinoplasty":"비성형술",
"Facelift":"페이스리프트",
"Program Lead":"프로그램 리드",
"Professor, Dept. of Plastic Surgery":"성형외과 교수",
"Clinical Director · KSAPS Member":"임상 디렉터 · KSAPS 회원",
"Thread lifting & filler specialist":"실리프팅 & 필러 전문",
"Thread lifting":"실리프팅",
"Bio-filler · BIOSTER":"바이오필러 · BIOSTER",
"International Exchange, KSAPS":"KSAPS 국제교류",
"Dermatology · Laser specialist":"피부과 · 레이저 전문",
"Pico laser":"피코 레이저",
"CO₂ Fractional":"CO₂ 프락셔널",
"Bio-stimulator & regenerative medicine":"바이오스티뮬레이터 & 재생의학",
"Bio-stimulator":"바이오스티뮬레이터",
"Regenerative medicine":"재생의학",
"Head of Participation · SNUBH":"참여 책임자 · SNUBH",
"Bio-filler clinical research lead":"바이오필러 임상 연구 리드",
"Collagen induction":"콜라겐 유도",
"Aesthetic surgery & protocol":"미용성형 & 프로토콜",
"Surgical protocol":"수술 프로토콜",
"Facial contouring":"안면 윤곽",
"Summit Day 2 tracks · KAT hands-on":"서밋 2일차 트랙 · KAT 핸즈온",
"Hands-on Track A":"핸즈온 Track A",
"Track B":"Track B",
"Track C":"Track C",
"Live surgery":"라이브 수술",
"Summit Day 2":"서밋 2일차",
"Vietnamese partner":"베트남 파트너",
"The Vietnam Society of Aesthetic Plastic Surgery (VSAPS) is the official Vietnamese partner for K-Beauty MEETS 2026. Founded in 2007 and recognized by Vietnam's Ministry of Health, VSAPS is the central organizing body for aesthetic surgery in Vietnam.":"베트남미용성형외과학회(VSAPS)는 K-Beauty MEETS 2026의 공식 베트남 파트너입니다. 2007년에 설립되어 베트남 보건부의 인정을 받은 VSAPS는 베트남 미용성형의 중심 조직입니다.",
"The KSAPS-VSAPS partnership MOU was signed at APS Korea 2026 in April — with VSAPS president Dr. Lê Hành and 23 VSAPS board members and representatives attending the ceremony in Seoul. This gives K-Beauty MEETS direct access to Vietnam's entire aesthetic surgery community.":"KSAPS-VSAPS 파트너십 MOU는 2026년 4월 서울 APS Korea 2026에서 체결되었습니다 — VSAPS 회장 Dr. Lê Hành과 23명의 이사회 멤버 및 대표가 참석했습니다. 이를 통해 K-Beauty MEETS는 베트남 전체 미용성형 커뮤니티에 직접 접근할 수 있게 되었습니다.",
"Actively co-initiated the K-Beauty MEETS partnership. Signed the KSAPS-VSAPS MOU at APS Korea 2026 in April. Committed to integrating Korean academic sessions as dedicated tracks within the VSAPS annual congress framework.":"K-Beauty MEETS 파트너십을 공동 추진했습니다. 2026년 4월 APS Korea 2026에서 KSAPS-VSAPS MOU에 서명했으며, VSAPS 연례 학술대회 안에 한국 학술 세션을 전용 트랙으로 통합하는 데 전념하고 있습니다.",
"One of Vietnam's most prestigious military hospitals. Purpose-built for events at this scale — 3 conference rooms, full OR suites with live broadcast, a large exhibition hall, and experienced staff in international medical events. Located in Ho Chi Minh City.":"베트남에서 가장 권위 있는 군 병원 중 하나입니다. 이 규모의 행사를 위해 3개 컨퍼런스룸, 라이브 방송 가능한 수술실, 대형 전시장, 국제 의료행사 경험이 풍부한 스태프를 갖추고 있습니다. 호치민시에 위치합니다.",
"Register for":"등록:",
"Select one, two, or all three. You fill in your information once — KBIT will review and send a separate QR ticket for each event you are confirmed for.":"하나, 둘, 또는 세 개 행사를 선택하세요. 정보를 한 번만 입력하면 KBIT이 검토 후 확인된 각 행사에 대해 별도의 QR 티켓을 보내드립니다.",
"October 3, 2026 · Kangnam Aesthetic Hospital, Ho Chi Minh City":"2026년 10월 3일 · 강남미용성형병원, 호치민시",
"· 10:00 Scientific Lectures (×4)":"· 10:00 학술 강연 (×4)",
"Room A — Live Device Demo + Botox & Filler Live":"Room A — 라이브 기기 시연 + 보톡스 & 필러 라이브",
"Room B — Live Plastic Surgery (OR broadcast)":"Room B — 라이브 성형수술 (OR 방송)",
"October 17–18, 2026 · 108 Military Central Hospital, Hanoi":"2026년 10월 17–18일 · 108 중앙군사병원, 하노이",
"~1,000 delegates":"약 1,000명 참가",
"Room A — Medical Devices":"Room A — 의료기기",
"Room B — Aesthetic Surgery":"Room B — 미용성형",
"Room C — Korean Protocols":"Room C — 한국 프로토콜",
"~150 VIP guests · Separate review by KBIT":"VIP 약 150명 · KBIT 별도 심사",
"This information applies to all events you selected. Fill in once — KBIT will use this to generate your QR tickets.":"이 정보는 선택한 모든 행사에 적용됩니다. 한 번만 입력하면 KBIT이 QR 티켓 생성에 사용합니다.",
"Da Nang":"다낭",
"Can Tho":"껀터",
"Aesthetic / Plastic Surgery":"미용 / 성형외과",
"Dermatology":"피부과",
"General Practice":"일반 진료",
"Clinic Manager":"클리닉 매니저",
"Distributor":"유통사",
"Help KBIT understand your clinical interests to improve matching and session recommendations.":"임상 관심 분야를 알려주시면 KBIT이 매칭과 세션 추천을 개선할 수 있습니다.",
"Thread lifting PCL/PDO":"PCL/PDO 실리프팅",
"Bio-stimulator / BIOSTER":"바이오스티뮬레이터 / BIOSTER",
"Email:":"이메일:",
"City:":"도시:",
"Confirmation and QR tickets sent within":"확인 메일과 QR 티켓은 제출 후",
"after submission.":"이내 발송됩니다.",
"One QR ticket generated per event selected. Each QR is unique to you.":"선택한 행사별로 QR 티켓이 하나씩 생성됩니다. 각 QR은 본인 전용입니다.",
"Registration deadlines:":"등록 마감:",
"Summit Sep 26 · KAT Sep 27 · Congress Oct 17.":"서밋 9월 26일 · KAT 9월 27일 · 학술대회 10월 17일.",
"in advance. No-shows without notice affect priority at future events.":"사전에 알려주세요. 사전 통보 없는 불참은 향후 행사 우선순위에 영향을 미칩니다.",
"Data:":"데이터:",
"Your information is shared only with KSAPS, SNUBH, VSAPS, KBIT, and KHIDI for registration and CME purposes. Not shared with any other party.":"귀하의 정보는 등록 및 CME 목적을 위해 KSAPS, SNUBH, VSAPS, KBIT, KHIDI와만 공유되며, 다른 제3자에게 공유되지 않습니다.",
"I consent to my personal information — name, email, phone, hospital, specialty — being shared with the Organizing Committee (KSAPS · SNUBH · VSAPS · KBIT · KHIDI) for the purposes of event registration, attendance tracking, and CME certificate issuance. My data will not be shared with any third parties beyond these organizing bodies. I may contact":"이름, 이메일, 전화번호, 병원, 전공 등 개인정보가 행사 등록, 출석 확인, CME 수료증 발급을 위해 조직위원회(KSAPS · SNUBH · VSAPS · KBIT · KHIDI)에 공유되는 데 동의합니다. 해당 기관 외 제3자에게 공유되지 않으며, 행사 후 삭제 요청은",
"to request deletion after the event.":"로 문의할 수 있습니다.",
"I have read and agree to the attendance policy. I will notify KBIT if I am unable to attend any confirmed event.":"참석 정책을 읽고 동의합니다. 확정된 행사에 참석할 수 없는 경우 KBIT에 알리겠습니다.",
"Questions? Contact Registration team at":"문의: 등록팀",
"Oct 3 · Kangnam AH · HCMC":"10월 3일 · 강남 AH · 호치민시",
"Oct 4 · HCMC":"10월 4일 · 호치민시",
"Oct 17–18 · 108 MCH · Hanoi":"10월 17–18일 · 108 MCH · 하노이",
"Sep 26, 2026":"2026년 9월 26일",
"Sep 27, 2026":"2026년 9월 27일",
"Oct 17, 2026":"2026년 10월 17일",
"~1,000 delegates · Exhibition · Industry Symposium":"약 1,000명 참가 · 전시 · 인더스트리 심포지엄",
"confirmation after application.":"신청 후 확인.",
"Please provide your data consent to continue.":"계속하려면 개인정보 동의가 필요합니다.",
"Please agree to the attendance policy before submitting.":"제출 전 참석 정책에 동의해 주세요.",
"Register Meeting":"미팅 등록",
"Register Free":"무료 등록",
"Register now — Free":"지금 등록 — 무료",
"Register now — Free →":"지금 등록 — 무료 →",
"Register now — It's free →":"지금 등록 — 무료 →",
"Register to attend →":"참가 등록 →",
"Register Congress →":"학술대회 등록 →",
"Register KAT":"KAT 등록",
"Register for KAT 2026 →":"KAT 2026 등록 →",
"Register for KAT Vietnam 2026 →":"KAT 베트남 2026 등록 →",
"Register for Business Meeting →":"비즈니스 미팅 등록 →",
"Register for Congress & KAT →":"학술대회 & KAT 등록 →",
"Register for KAT Vietnam Oct 4 →":"KAT 베트남 10월 4일 등록 →",
"Register for Congress Oct 17–18 →":"10월 17–18일 학술대회 등록 →",
"View program":"프로그램 보기",
"View program ↓":"프로그램 보기 ↓",
"View schedule ↓":"일정 보기 ↓",
"View event formats ↓":"행사 형식 보기 ↓",
"View all →":"전체 보기 →",
"View all 15 speakers →":"전체 15명 연사 보기 →",
"Learn more":"자세히 보기",
"Explore Summit →":"서밋 둘러보기 →",
"Supported by":"후원",
"Organized by":"주최",
"Korea Ministry of Health & Welfare":"대한민국 보건복지부",
"Ho Chi Minh City":"호치민시",
"Ho Chi Minh City, Vietnam":"호치민시, 베트남",
"Hanoi":"하노이",
"HCMC":"호치민시",
"Vietnam":"베트남",
"Korea":"한국",
"Other":"기타",
"K-Beauty MEETS 2026 · Business Program":"K-Beauty MEETS 2026 · 비즈니스 프로그램",
"Meet the decision-makers.":"의사결정권자를 만나고",
"Close the deal.":"계약으로 연결하세요.",
"K-Beauty MEETS 2026 brings 1,000+ Vietnamese aesthetic physicians and clinic decision-makers to three events across Ho Chi Minh City and Hanoi. Register your company for a structured 1:1 Business Meeting — KBIT will facilitate the connection.":"K-Beauty MEETS 2026은 호치민시와 하노이의 세 행사에 베트남 미용의학 의사 및 클리닉 의사결정권자 1,000명 이상을 초대합니다. 구조화된 1:1 비즈니스 미팅에 회사를 등록하면 KBIT이 연결을 지원합니다.",
"KSAPS Summit · Oct 3 · HCMC":"KSAPS 서밋 · 10월 3일 · 호치민시",
"KAT Vietnam · Oct 4 · HCMC":"KAT 베트남 · 10월 4일 · 호치민시",
"KSAPS Congress · Oct 17–18 · Hanoi":"KSAPS 학술대회 · 10월 17–18일 · 하노이",
"Business Meeting Program":"비즈니스 미팅 프로그램",
"Structured access to":"체계적인 접근",
"Vietnam's":"베트남",
"top aesthetic clinics":"최고 미용 클리닉",
"The Business Meeting Program gives Korean medical device companies direct, scheduled 1:1 sessions with Vietnamese hospital directors, clinic owners, and purchasing managers attending K-Beauty MEETS events. KBIT facilitates the matching and scheduling.":"비즈니스 미팅 프로그램은 한국 의료기기 기업에게 K-Beauty MEETS 행사에 참석하는 베트남 병원장, 클리닉 원장, 구매 담당자와의 예약제 1:1 미팅을 제공합니다. KBIT이 매칭과 일정을 조율합니다.",
"Facilitated 1:1 Matching":"맞춤형 1:1 매칭",
"KBIT reviews your company profile and meeting objectives, then matches you with pre-qualified Vietnamese buyers — hospital directors, clinic owners, and medical equipment purchasing managers actively attending the event.":"KBIT이 기업 프로필과 미팅 목표를 검토한 뒤, 행사에 참석하는 검증된 베트남 바이어 — 병원장, 클리닉 원장, 의료장비 구매 담당자 — 와 매칭합니다.",
"Scheduled & Pre-confirmed":"사전 일정 확정",
"30-minute dedicated sessions during lunch breaks and coffee breaks at each event. All meetings pre-confirmed by both parties. Dedicated interpreter available. On-site LOI signing facilitated for serious purchase intent.":"각 행사 점심 및 커피 브레이크 시간에 30분 전용 세션을 운영합니다. 모든 미팅은 양측 사전 확인 후 진행되며, 전담 통역과 구매 의향이 있는 경우 현장 LOI 체결 지원이 제공됩니다.",
"3 Events · 2 Cities":"3개 행사 · 2개 도시",
"Register for one, two, or all three events. Each event reaches a different segment of Vietnam's aesthetic medical market — HCMC specialists at Summit and KAT, Hanoi and nationwide delegates at Congress.":"1개, 2개 또는 3개 행사 모두 등록할 수 있습니다. 각 행사는 베트남 미용의학 시장의 다른 세그먼트에 접근합니다 — 서밋과 KAT은 호치민시 전문의, 학술대회는 하노이 및 전국 참가자 중심입니다.",
"Meeting slots by event":"행사별 미팅 슬롯",
"Choose your":"선택하세요",
"event(s)":"참가 행사",
"Each event has a different scale and audience. Meeting slots are limited — early registration is recommended.":"각 행사는 규모와 대상이 다릅니다. 미팅 슬롯이 한정되어 있어 조기 등록을 권장합니다.",
"HCMC · Specialist":"호치민시 · 전문의",
"October 3, 2026 · 1 day":"2026년 10월 3일 · 1일",
"Kangnam Aesthetic Hospital, Ho Chi Minh City":"강남미용성형병원, 호치민시",
"100 specialist doctors (plastic surgery, dermatology)":"전문의 100명 (성형외과, 피부과)",
"Press conference + Lecture + Live Device Demo":"기자회견 + 강연 + 라이브 기기 시연",
"High-value, decision-maker focused audience":"의사결정권자 중심의 고가치 참가자",
"Meeting slots available":"예약 가능한 미팅 슬롯",
"1:1 Business Meeting (30 min)":"1:1 비즈니스 미팅 (30분)",
"6 slots left":"6개 슬롯 남음",
"LOI Facilitation":"LOI 지원",
"Available":"가능",
"Device Demo Slot":"기기 시연 슬롯",
"3 slots left":"3개 슬롯 남음",
"HCMC · Hands-on":"호치민시 · 핸즈온",
"October 4, 2026":"2026년 10월 4일",
"Aesthetic doctors seeking hands-on training":"실습 교육을 원하는 미용의학 의사",
"Live Device Demo · Botox & Filler Live":"라이브 기기 시연 · 보톡스 & 필러 라이브",
"Direct device experience in clinical setting":"임상 환경에서의 직접 기기 경험",
"Hanoi · Flagship":"하노이 · 플래그십",
"October 17–18, 2026 · 2 days":"2026년 10월 17–18일 · 2일",
"108 Military Central Hospital, Hanoi":"108 중앙군사병원, 하노이",
"~1,000 delegates nationwide + international":"국내외 참가자 약 1,000명",
"Exhibition booths + Industry Symposia":"전시 부스 + 인더스트리 심포지엄",
"VIP Gala Dinner · Maximum B2B exposure":"VIP 갈라 디너 · 최대 B2B 노출",
"Exhibition Booth":"전시 부스",
"4 booths left":"4개 부스 남음",
"Industry Symposium (30 min)":"인더스트리 심포지엄 (30분)",
"Gala Dinner Table":"갈라 디너 테이블",
"Limited":"한정",
"Participating companies":"참가 기업",
"10 Korean companies":"한국 기업 10개사",
"already confirmed":"참가 확정",
"10 Korean medical device":"한국 의료기기",
"companies at Congress":"학술대회 참가 기업 10개사",
"These companies have confirmed participation. If your company is not listed, you can still register — KBIT will review and add qualified Korean medical device companies to the program.":"아래 기업은 참가가 확정되었습니다. 목록에 없는 기업도 등록할 수 있으며, KBIT이 검토 후 적합한 한국 의료기기 기업을 프로그램에 추가합니다.",
"Why register early":"왜 조기 등록해야 하나요?",
"Meeting slots are limited per event":"행사별 미팅 슬롯이 한정되어 있습니다",
"KBIT matching is first-come, best-matched":"KBIT 매칭은 선착순 및 적합도 기준으로 진행됩니다",
"Industry Symposium slots at Congress are filling":"학술대회 인더스트리 심포지엄 슬롯이 빠르게 차고 있습니다",
"Exhibition booth at Congress: 4 spots remaining":"학술대회 전시 부스: 4개 남음",
"Business Meeting Registration":"비즈니스 미팅 등록",
"Register your company":"기업 등록",
"Fill in your company details and select which events you want to attend. KBIT will review your registration and confirm your meeting schedule within 3–5 business days.":"기업 정보를 입력하고 참가할 행사를 선택하세요. KBIT이 등록을 검토하고 3~5 영업일 이내에 미팅 일정을 확정합니다.",
"Events":"행사",
"Company":"기업",
"Objectives":"목표",
"Confirm":"확인",
"Select events to attend":"참가 행사 선택",
"— choose one or more":"— 하나 이상 선택",
"Company information":"기업 정보",
"Company name":"기업명",
"Country":"국가",
"Contact person":"담당자",
"Position / Title":"직책 / 직함",
"Email":"이메일",
"Phone / WhatsApp":"전화 / WhatsApp",
"Main product(s) / Category":"주요 제품 / 카테고리",
"Website":"웹사이트",
"Type of meeting requested":"요청 미팅 유형",
"— select all that apply":"— 해당 항목 모두 선택",
"1:1 Business Meeting":"1:1 비즈니스 미팅",
"30-min scheduled session with Vietnamese hospital/clinic buyer. KBIT-matched and pre-confirmed.":"베트남 병원/클리닉 바이어와의 30분 예약 세션. KBIT 매칭 및 사전 확정.",
"Live demonstration of your device in the event's dedicated demo area. KOL-supported optional.":"행사 전용 시연 공간에서 기기를 라이브로 시연합니다. KOL 지원은 선택 사항입니다.",
"Industry Symposium":"인더스트리 심포지엄",
"30-min dedicated session in Room A at Congress (Hanoi). Full audience + Q&A.":"하노이 학술대회 Room A에서 진행되는 30분 전용 세션. 전체 청중 대상 + Q&A.",
"Dedicated booth at KSAPS Congress (Hanoi). Open throughout both days.":"하노이 KSAPS 학술대회 전용 부스. 양일간 운영.",
"Meeting objectives & target buyers":"미팅 목표 및 타깃 바이어",
"Who do you want to meet?":"만나고 싶은 대상",
"Hospital directors / Clinic owners":"병원장 / 클리닉 원장",
"Purchasing managers":"구매 담당자",
"Distributors / Importers":"유통사 / 수입사",
"Aesthetic surgeons":"미용성형 외과의",
"All of the above":"위 모두",
"Meeting objectives / What do you hope to achieve?":"미팅 목표 / 기대 성과",
"Any specific companies or clinics you want to meet?":"만나고 싶은 특정 기업 또는 클리닉",
"Business Meeting Policy":"비즈니스 미팅 정책",
"KBIT reviews all registrations and confirms participation within 3–5 business days.":"KBIT은 모든 등록을 검토하고 3~5 영업일 이내에 참가 여부를 확정합니다.",
"Meeting matches are facilitated by KBIT — you will receive a confirmed schedule before each event.":"미팅 매칭은 KBIT이 지원하며, 각 행사 전 확정 일정을 받게 됩니다.",
"Interpretation support provided at all meetings (Korean ↔ Vietnamese).":"모든 미팅에 통역 지원이 제공됩니다 (한국어 ↔ 베트남어).",
"KBIT does not guarantee specific buyer attendance — all meetings are pre-confirmed with both parties.":"KBIT은 특정 바이어 참석을 보장하지 않습니다. 모든 미팅은 양측 사전 확인 후 진행됩니다.",
"I have read and agree to the Business Meeting Policy. I understand that KBIT will review my registration before confirmation.":"비즈니스 미팅 정책을 읽고 동의합니다. KBIT이 확정 전 등록을 검토한다는 점을 이해합니다.",
"Submit Business Meeting Registration →":"비즈니스 미팅 등록 제출 →",
"Facilitated by KBIT":"KBIT 지원",
"Korea Business & Industry Training":"Korea Business & Industry Training",
"Summit + KAT":"서밋 + KAT",
"Oct 3 + Oct 4":"10월 3일 + 10월 4일",
"Oct 17–18 · 108 Military Hospital":"10월 17–18일 · 108 중앙군사병원",
"Total reach":"총 접근 규모",
"1,200+ medical professionals":"의료 전문가 1,200명 이상",
"Across all 3 events":"전체 3개 행사 합산",
"What KBIT provides":"KBIT 제공 서비스",
"✓ Buyer matching & pre-scheduling":"✓ 바이어 매칭 & 사전 일정",
"✓ Korean ↔ Vietnamese interpretation":"✓ 한국어 ↔ 베트남어 통역",
"✓ Meeting room / space at venue":"✓ 행사장 내 미팅룸 / 공간",
"✓ LOI documentation support":"✓ LOI 문서 지원",
"✓ Post-event follow-up facilitation":"✓ 행사 후 후속 지원",
"✓ Export consultation report":"✓ 수출 상담 보고서",
"Questions?":"문의",
"Registration team":"등록팀",
"Response within 1–2 business days":"1~2 영업일 이내 회신",
"Summit Oct 3":"서밋 10월 3일",
"KAT Oct 4":"KAT 10월 4일",
"Congress Oct 17–18":"학술대회 10월 17–18일",
"The Flagship":"대표",
"of":"행사",
"What is KSAPS Congress?":"KSAPS 학술대회란?",
"A full day of":"하루 종일",
"Korean aesthetic":"한국 미용",
"medicine":"의학",
"3 Parallel rooms — choose your track":"3개 병행 트랙 — 선택하세요",
"Room A covers medical devices and energy-based technology. Room B focuses on aesthetic surgery. Room C delivers Korean clinical protocols for injectables and non-invasive treatments.":"Room A는 의료기기 및 에너지 기반 기술, Room B는 미용성형, Room C는 주사제 및 비수술 시술을 위한 한국 임상 프로토콜을 다룹니다.",
"Exhibition zone with 15+ Korean medical device companies. B2B matching area, KOL-certified user programs, and LOI signing for distribution agreements.":"한국 의료기기 기업 15개사 이상이 참여하는 전시 구역입니다. B2B 매칭, KOL 인증 사용자 프로그램, 유통 계약 LOI 체결을 지원합니다.",
"Exclusive networking dinner for 150–200 guests the evening of October 17. Priority given to specialist physicians and Congress + KAT combo registrants.":"10월 17일 저녁 150~200명 VIP 전용 네트워킹 디너입니다. 전문의와 학술대회 + KAT 콤보 등록자를 우선합니다.",
"KSAPS Congress 2026 certificate issued by KSAPS & KBIT. CME Certificate issued after the event.":"KSAPS & KBIT 명의의 KSAPS 학술대회 2026 수료증과 행사 후 CME 수료증이 발급됩니다.",
"Program Structure":"프로그램 구성",
"3 rooms. All day.":"3개 트랙. 종일.",
"Your":"나에게 맞는",
"choice":"선택",
"of depth.":"깊이.",
"Three fully parallel tracks run simultaneously throughout the day. Move between rooms or commit to one — the choice is yours. Each room is designed as a self-contained learning experience.":"3개의 완전한 병행 트랙이 종일 동시에 운영됩니다. 트랙 간 이동하거나 하나에 집중할 수 있으며, 각 트랙은 독립적인 학습 경험으로 설계되었습니다.",
"Medical Devices":"의료기기",
"EBD Master Class · Industry Symposia":"EBD 마스터 클래스 · 인더스트리 심포지엄",
"Aesthetic Surgery":"미용성형",
"Korean surgical standards · Live case discussion":"한국 수술 표준 · 라이브 케이스 토론",
"Korean Protocols":"한국 프로토콜",
"Injectables · Non-invasive · Panel Q&A":"주사제 · 비수술 · 패널 Q&A",
"Full program":"전체 프로그램",
"October 17–18, 2026 —":"2026년 10월 17–18일 —",
"2 days":"2일",
"Day 1 · Saturday, October 17":"1일차 · 토요일, 10월 17일",
"Day 2 · Sunday, October 18":"2일차 · 일요일, 10월 18일",
"Academic Sessions · 3 Parallel Rooms · Exhibition · Gala Dinner":"학술 세션 · 3개 병행 트랙 · 전시 · 갈라 디너",
"Registration · Exhibition zone opens · Networking coffee":"등록 · 전시 구역 오픈 · 네트워킹 커피",
"Opening Plenary":"개회 전체 세션",
"Welcome remarks — KBIT CEO · KSAPS President · VSAPS President (Prof. Dr. Lê Hành)":"환영사 — KBIT CEO · KSAPS 회장 · VSAPS 회장 (Prof. Dr. Lê Hành)",
"Introduction of Korean KOL delegation · Group photo":"한국 KOL 대표단 소개 · 단체 사진",
"Plenary":"전체 세션",
"Academic Session I — Korea–Vietnam Cross Lectures":"학술 세션 I — 한·베 교차 강연",
"HIFU · RF Lifting — Korean KOL (1)":"HIFU · RF 리프팅 — 한국 KOL (1)",
"Rhinoplasty Clinical Updates — Korean KOL (2)":"비성형술 임상 업데이트 — 한국 KOL (2)",
"Vietnamese Clinical Case Presentation — VN Speaker":"베트남 임상 케이스 발표 — 베트남 연자",
"Thread Lifting & Filler Combination — Korean KOL (3)":"실리프팅 & 필러 복합 시술 — 한국 KOL (3)",
"Panel Discussion · Q&A":"패널 토론 · Q&A",
"Plenary Hall":"전체 세션 홀",
"VIP Lunch (speakers) · General lunch · Exhibition free viewing · Industry Meet & Greet":"VIP 점심(연자) · 일반 점심 · 전시 자유 관람 · 인더스트리 밋앤그릿",
"3 Parallel Rooms":"3개 병행 트랙",
"Medical Device & Technology Symposium":"의료기기 & 기술 심포지엄",
"Industry Symposia × 10 companies":"인더스트리 심포지엄 × 10개사",
"Academic Session II":"학술 세션 II",
"Korea–Vietnam cross lectures":"한·베 교차 강연",
"Skin regeneration · Anti-aging":"피부 재생 · 안티에이징",
"Dermatology & Skin Care":"피부과 & 스킨케어",
"Symposium":"심포지엄",
"Networking Reception — Company reps × Doctors × KSAPS/VSAPS board":"네트워킹 리셉션 — 기업 담당자 × 의사 × KSAPS/VSAPS 이사회",
"~150 VIP guests · Speakers · KSAPS/VSAPS board · Company representatives":"VIP 약 150명 · 연자 · KSAPS/VSAPS 이사회 · 기업 대표",
"Partnership agreement signing ceremony (if applicable)":"파트너십 협약식 (해당 시)",
"Hands-on Workshop · Live Surgery · CME Certificate":"핸즈온 워크숍 · 라이브 수술 · CME 수료증",
"Registration · Exhibition reopens":"등록 · 전시 재오픈",
"Parallel Sessions":"병행 세션",
"Room A — Hands-on":"Room A — 핸즈온",
"Room B — Live Surgery":"Room B — 라이브 수술",
"Live Plastic Surgery Demo":"라이브 성형수술 시연",
"KSAPS KOL performing":"KSAPS KOL 집도",
"OR → Main hall live broadcast":"수술실 → 메인홀 라이브 방송",
"Step-by-step + Q&A":"단계별 해설 + Q&A",
"Lunch · Last exhibition viewing · 1:1 B2B meetings (pre-booked)":"점심 · 마지막 전시 관람 · 1:1 B2B 미팅 (사전 예약)",
"Afternoon Workshop — Parallel 2 rooms":"오후 워크숍 — 2개 병행룸",
"Room A: Laser & Energy device hands-on (company-sponsored)":"Room A: 레이저 & 에너지 기기 핸즈온 (기업 후원)",
"Room B: Korean Clinical Protocol — Dermatology & Spa operators":"Room B: 한국 임상 프로토콜 — 피부과 & 스파 운영자",
"Closing Ceremony":"폐회식",
"CME Certificate presentation · Company appreciation awards":"CME 수료증 수여 · 기업 감사패",
"Closing remarks — KBIT · KSAPS · VSAPS":"폐회사 — KBIT · KSAPS · VSAPS",
"Next event announcement (VSAPS December Congress)":"다음 행사 안내 (VSAPS 12월 학술대회)",
"Korean KOL":"한국 KOL",
"presenting at":"발표 연자",
"Congress":"학술대회",
"+ 8 more KOL":"추가 KOL 8명",
"Attendance Policy":"참석 정책",
"KSAPS Congress is free to attend for all Vietnamese medical professionals — funded by KHIDI. Seats are limited and subject to review by the KBIT Organizing Committee.":"KSAPS 학술대회는 KHIDI 지원으로 베트남 의료 전문가 전원 무료입니다. 좌석은 한정되어 있으며 KBIT 조직위원회 심사 대상입니다.",
"confirmation after application":"신청 후 확인",
"reviewed separately — priority for specialist doctors and combo registrants":"별도 심사 — 전문의 및 콤보 등록자 우선",
"Can't attend?":"참석이 어렵습니까?",
"Email us in advance":"사전에 이메일로 알려주세요",
"No-shows without notice affect":"사전 통보 없는 불참은",
"priority at future events":"향후 행사 우선순위에 영향을 줍니다",
"Join KSAPS Congress 2026":"KSAPS 학술대회 2026 참가",
"October 17 · 108 Military Central Hospital":"10월 17일 · 108 중앙군사병원",
"Hanoi, Vietnam":"하노이, 베트남",
"Free to attend · Limited seats · Application-based":"무료 참가 · 좌석 한정 · 심사 기반",
"Attending the day after?":"다음 날도 참가하시나요?",
"Korean":"한국",
"Aesthetic Standards":"미용의학 기준",
"Direct access to Korean KOL":"한국 KOL 직접 교류",
"K-Standard protocols, not theory":"이론이 아닌 K-스탠다드 프로토콜",
"Government-backed, free to attend":"정부 지원, 무료 참가",
"KHIDI Funded":"KHIDI 지원",
"Free to attend":"무료 참가",
"2026 Series":"2026 시리즈",
"Two cities. Three events.":"두 도시. 세 개의 행사.",
"One":"하나의",
"movement.":"움직임.",
"From an intimate clinical workshop in Ho Chi Minh City to Vietnam's largest Korean aesthetic congress in Hanoi — K-Beauty MEETS 2026 spans two cities and four days.":"호치민시의 집중 임상 워크숍부터 하노이의 베트남 최대 한국 미용의학 학술대회까지 — K-Beauty MEETS 2026은 두 도시, 나흘에 걸쳐 진행됩니다.",
"Free":"무료",
"· Limited 100":"· 100명 한정",
"· Limited seats":"· 좌석 한정",
"Korea's training series —":"한국의 교육 시리즈 —",
"expanding across Asia":"아시아로 확장",
"Completed":"완료",
"Coming soon":"출시 예정",
"Registration open":"등록 진행 중",
"Next destination — TBA":"다음 개최지 — 추후 공개",
"Stay tuned":"추후 공개",
"KAT 2025 — Proven results":"KAT 2025 — 검증된 실적",
"Results that speak":"스스로 말하는",
"for themselves":"실적",
"Doctors trained on-site":"현장 교육 의사 수",
"Export consultations achieved":"수출 상담 실적",
"Distributors follow-up requests":"유통업체 후속 요청",
"Hospitals partnership requests":"병원 파트너십 요청",
"Speakers":"연사진",
"15 Korean KOL from KSAPS &":"KSAPS &",
"+ 9 more →":"+ 9명 더 보기 →",
"Free to attend":"무료 참가",
"Limited seats · Application review":"좌석 한정 · 심사 등록",
"No-show policy":"불참 정책",
"Partners & Sponsors":"파트너 & 후원",
"Ho Chi Minh City + Hanoi · October 2026":"호치민시 + 하노이 · 2026년 10월",
"More":"더보기",
"Contact KBIT":"KBIT 문의",
"© 2026 K-Beauty MEETS · Coordinated by KBIT":"© 2026 K-Beauty MEETS · KBIT 주관",
"Vietnam":"베트남",
"At a glance":"한눈에 보기",
"Doctors":"의사",
"Parallel rooms":"병행 트랙",
"Live surgery cases":"라이브 수술 건수",
"KOL to doctor":"KOL 대 의사",
"What you'll get":"포함 내용",
"What makes KAT different":"KAT의 차별점",
"Skills, not":"슬라이드가 아닌",
"slides.":"실습.",
"Live surgery in real time":"실시간 라이브 수술",
"Hands-on with direct Korean KOL guidance":"한국 KOL 직접 지도 핸즈온",
"Day 2 of a 2-day journey":"2일 여정의 2일차",
"The program":"프로그램",
"Two rooms running":"두 개 룸이",
"in parallel —":"병행 운영 —",
"all day.":"종일.",
"Room summary":"룸 요약",
"Live Demo & Hands-on":"라이브 시연 & 핸즈온",
"Device demos · Botox · Filler · Small-group practice":"기기 시연 · 보톡스 · 필러 · 소그룹 실습",
"Live Plastic Surgery":"라이브 성형수술",
"4 surgeries · UHD OR broadcast · Real-time Q&A":"수술 4건 · UHD 수술실 방송 · 실시간 Q&A",
"Coffee Break + Free Practice":"커피 브레이크 + 자유 실습",
"Break":"휴식",
"Lunch · Devices open for free practice":"점심 · 기기 자유 실습",
"Korea's medical":"한국의 의료",
"training network —":"교육 네트워크 —",
"Last year's KAT set the benchmark":"지난 KAT이 기준을 세웠습니다",
"The most hands-on day":"가장 실습 중심의 하루",
"of K-Beauty MEETS":"K-Beauty MEETS 중",
"Coming the day before?":"전날도 참가하시나요?",
"Korean Society of Aesthetic Plastic Surgery":"대한미용성형외과학회",
"Seoul National Univ. Bundang Hospital":"분당서울대학교병원",
"All KOL":"전체 KOL",
"Surgery":"수술",
"Devices":"기기",
"Specialty & topics":"전공 & 주제",
"Participating events":"참가 행사",
"Specialty & Topics":"전공 & 주제",
"Coverage":"담당 분야",
"7 Additional KOL":"추가 KOL 7명",
"Hands-on track instructors":"핸즈온 트랙 강사",
"VSAPS —":"VSAPS —",
"The gateway":"관문",
"to Vietnam's aesthetic surgeons":"베트남 미용성형 외과의로",
"of Vietnam's aesthetic surgeons are VSAPS members":"베트남 미용성형 외과의가 VSAPS 회원",
"Active member doctors — all clinical decision-makers":"활동 회원 의사 — 모두 임상 의사결정자",
"Founded · Vietnam Ministry of Health recognized":"설립 · 베트남 보건복지부 인정",
"Annual congress milestone — 2026":"연례 학술대회 10회 달성 — 2026",
"President, VSAPS":"VSAPS 회장",
"Program Coordinator, VSAPS · K-Beauty MEETS Liaison":"프로그램 코디네이터, VSAPS · K-Beauty MEETS 연락 담당",
"Host venue · KSAPS Congress + KAT Vietnam 2026":"개최지 · KSAPS 학술대회 + KAT 베트남 2026",
"Meet these doctors":"이 의사들을 만나세요",
"in Ho Chi Minh City":"호치민시에서",
"Register Summit":"서밋 등록",
"Register Congress":"학술대회 등록",
"K-Beauty MEETS":"K-Beauty MEETS",
"October 3, 2026":"2026년 10월 3일",
"Kangnam Aesthetic Hospital, HCMC":"강남미용성형병원, 호치민시",
"100 doctors · 1 day":"의사 100명 · 1일",
"K-Protocol Certificate":"K-프로토콜 수료증",
"Days · 2 venues":"일 · 장소 2곳",
"Max attendance":"최대 참가 인원",
"What's included":"포함 내용",
"Program":"프로그램",
"Full-day program":"종일 프로그램",
"Morning":"오전",
"Afternoon":"오후",
"Registration & Networking Coffee":"등록 & 네트워킹 커피",
"Delegate check-in · Name badges · Welcome refreshments":"참가 등록 · 명찰 · 환영 다과",
"Networking":"네트워킹",
"Opening Ceremony":"개회식",
"Welcome remarks — KSAPS · VSAPS · KBIT · Kangnam Aesthetic Hospital":"환영사 — KSAPS · VSAPS · KBIT · 강남미용성형병원",
"Group photo · Introduction of Korean KOL delegation":"단체 사진 · 한국 KOL 대표단 소개",
"Opening":"개회",
"Press Conference":"기자회견",
"Scientific Lectures — 4 sessions × 30 min":"학술 강연 — 4개 세션 × 30분",
"Scientific Lecture":"학술 강연",
"Lunch & Networking":"점심 & 네트워킹",
"Live Device Demo — 3 companies × 60 min":"라이브 기기 시연 — 3개사 × 60분",
"Live Demo":"라이브 시연",
"Live Surgery — Rhinoplasty":"라이브 수술 — 비성형술",
"Live Surgery · OR Broadcast":"라이브 수술 · OR 방송",
"Closing Ceremony & Certificate Presentation":"폐회식 & 수료증 수여",
"Closing · Certificate":"폐회 · 수료증",
"Venues":"개최지",
"Day 1 · October 3":"1일차 · 10월 3일",
"Day 2 · October 4":"2일차 · 10월 4일",
"Day 1 highlights":"1일차 하이라이트",
"Day 2 highlights":"2일차 하이라이트",
"Devices & technology":"기기 & 기술",
"6 Korean companies.":"한국 기업 6개사.",
"One clinical mission.":"하나의 임상 미션.",
"Devices in this event":"이 행사의 기기",
"at KSAPS Summit":"KSAPS 서밋",
"Built on a proven format":"검증된 형식 기반",
"Ready to learn from Korea's best?":"한국 최고의 전문가에게 배울 준비가 되셨습니까?",
"Select Events":"행사 선택",
"Your Details":"상세정보",
"Preferences":"관심 분야",
"Which event(s) would you like to attend?":"어떤 행사에 참석하시겠습니까?",
"Limited 100":"100명 한정",
"1 day":"1일",
"2 days":"2일",
"Summit program":"서밋 프로그램",
"Select preferred room":"선호 룸 선택",
"Both rooms":"두 룸 모두",
"Preferred rooms (Day 1 parallel sessions)":"선호 룸 (1일차 병행 세션)",
"VIP Gala Dinner — Evening Oct 17":"VIP 갈라 디너 — 10월 17일 저녁",
"(optional, limited)":"(선택, 한정)",
"Yes, I'd like to attend the Gala Dinner":"네, 갈라 디너에 참석하고 싶습니다",
"No, daytime only":"아니요, 낮 행사만 참석합니다",
"Please select at least one event to continue.":"계속하려면 최소 한 개 행사를 선택해 주세요.",
"Continue →":"계속 →",
"Personal information":"개인 정보",
"Full name":"성명",
"Email address":"이메일 주소",
"CME number / Medical license":"CME 번호 / 의사면허",
"Hospital / Clinic name":"병원 / 클리닉 이름",
"City":"도시",
"Specialty":"전공",
"Years of experience":"경력",
"Less than 2 years":"2년 미만",
"More than 10 years":"10년 이상",
"← Back":"← 뒤로",
"Topics & motivation":"관심 분야 & 참가 동기",
"Topics of interest":"관심 분야",
"(select all that apply)":"(해당 항목 모두 선택)",
"Korean rhinoplasty":"한국식 비성형술",
"Botox injection protocol":"보톡스 주사 프로토콜",
"Blepharoplasty":"안검성형",
"Filler — full face":"필러 — 전체 얼굴",
"Skin booster / PDRN":"스킨부스터 / PDRN",
"Combination protocols":"복합 프로토콜",
"Body contouring":"바디 컨투어링",
"Anti-aging protocols":"안티에이징 프로토콜",
"Why do you want to attend? What do you hope to gain?":"왜 참가하고 싶으신가요? 무엇을 얻고 싶으신가요?",
"Review application →":"신청서 검토 →",
"Review your application":"신청서 검토",
"Please confirm before submitting.":"제출 전 확인해 주세요.",
"Your details":"개인 정보",
"Name:":"이름:",
"Phone:":"전화:",
"Hospital:":"병원:",
"Specialty:":"전공:",
"All events are":"모든 행사는",
"free to attend":"무료 참가",
"— limited seats, reviewed by KBIT Organizing Committee.":"— 좌석 한정, KBIT 조직위원회 심사 대상입니다.",
"Data consent (required):":"개인정보 동의 (필수):",
"Submit application →":"신청서 제출 →",
"Application submitted!":"신청서가 제출되었습니다!",
"Thank you. KBIT will review your application and send confirmation with your QR ticket(s) within 3–5 business days. You will receive":"감사합니다. KBIT이 신청서를 검토하고 3~5 영업일 이내에 QR 티켓과 함께 확인 메일을 보내드립니다. 총",
"separate QR ticket(s) by email.":"개의 QR 티켓을 이메일로 받게 됩니다.",
"Your selected events":"선택한 행사",
"Registration deadlines":"등록 마감",
"All events include":"모든 행사 포함 사항",
"✓ Free to attend":"✓ 무료 참가",
"✓ CME Certificate issued":"✓ CME 수료증 발급",
"✓ QR ticket for entry":"✓ 입장용 QR 티켓",
"✓ Korean KOL speakers":"✓ 한국 KOL 연자",
"✓ KSAPS + KBIT organized":"✓ KSAPS + KBIT 주관",
"QR ticket":"QR 티켓",
"QR ticket will be emailed":"QR 티켓은 이메일로 발송됩니다",
"CME Certificate":"CME 수료증",
"Heo Chan-yeong":"허찬영",
"Kim Baek-gyu":"김백규",
"Park Young-jin":"박영진",
"Park Eun-su":"박은수",
"Seo Bo-mi":"서보미",
"Choi Jang-yeon":"최장연",
"Kim Jong-ho":"김종호",
"Lee Woo-sung":"이우성",
"Prof. Heo Chan-yeong":"허찬영 교수",
"Prof. Kim Baek-gyu":"김백규 교수",
"Dr. Park Young-jin":"박영진 원장",
"Prof. Park Eun-su":"박은수 교수",
"Prof. Seo Bo-mi":"서보미 교수",
"Prof. Choi Jang-yeon":"최장연 교수",
"Prof. Kim Jong-ho":"김종호 교수",
"Dr. Lee Woo-sung":"이우성 원장",
"HC":"허",
"KB":"김",
"KJ":"김",
"PY":"박",
"PE":"박",
"SB":"서",
"CJ":"최",
"LW":"이",
"Hironic":"하이로닉",
"Wontech":"원텍",
"Neodoctors":"네오닥터",
"Aestheform":"에스테팜",
"Roselab":"로즈랩",
"Samyang Biopharm":"삼양바이오팜",
"Lafullen · Croquis":"라풀렌 · 크로키",
"RecensMedical":"리센스메디컬",
"Meta Pharm":"메타약품",
"Antigravity":"안티그래비티",
"Osstem Pharma":"오스템파마",
"Hironic · DOUBLO":"하이로닉 · DOUBLO",
"Wontech · Oligio":"원텍 · Oligio",
"Neodoctors · JAMBER":"네오닥터 · JAMBER",
"Aestheform · QTFILL":"에스테팜 · QTFILL",
"Roselab · BIOSTER":"로즈랩 · BIOSTER"
};

window.KO_PH={
"Dr. Nguyen Van A":"Dr. Nguyen Van A",
"+84 912 345 678":"+84 912 345 678",
"doctor@clinic.com":"doctor@clinic.com",
"VN-CME-XXXXX":"VN-CME-XXXXX",
"Hospital or clinic name":"병원 또는 클리닉 이름",
"e.g. I want to learn Korean-standard Botox injection techniques and see live rhinoplasty to improve my practice...":"예: 한국 표준 보톡스 주사 기법을 배우고 라이브 비성형술을 보며 진료 수준을 높이고 싶습니다...",
"e.g. Hironic Co., Ltd.":"예: Hironic Co., Ltd.",
"Full name":"성명",
"e.g. Export Manager":"예: 수출 매니저",
"contact@company.com":"contact@company.com",
"+82 10 XXXX XXXX":"+82 10 XXXX XXXX",
"e.g. HIFU device, HA filler, thread lifting":"예: HIFU 기기, HA 필러, 실리프팅",
"https://":"https://",
"e.g. Find a local distributor for our RF device. Demonstrate clinical outcomes to 3–5 hospital buyers. Sign LOI for product trial at 2 HCMC clinics.":"예: RF 기기의 현지 유통사를 찾고, 병원 바이어 3~5명에게 임상 결과를 시연하며, 호치민시 클리닉 2곳과 제품 테스트 LOI를 체결하고 싶습니다.",
"Optional — if you have specific targets, we will try to arrange.":"선택 — 특정 타깃이 있으면 가능한 범위에서 조율합니다.",

// ===== LIBRARY PAGE =====
'lib.eyb':'K-BEAUTY MEETS · 라이브러리',
'lib.title':'<em>K-Beauty MEETS</em>의 순간들',
'lib.sub':'과거 행사 사진 및 하이라이트 — KSAPS 서밋, KAT 베트남, KSAPS 학술대회.',
'lib.filter':'필터:',
'lib.all':'전체',
'lib.f.summit':'KSAPS 서밋',
'lib.f.congress':'KSAPS 학술대회',
'lib.f.kat':'KAT 베트남',
'lib.s25.eyb':'KSAPS 서밋',
'lib.s25.loc':'호치민시',
'lib.s25.venue':'강남미용성형병원',
'lib.k25.eyb':'KAT 베트남',
'lib.k25.loc':'호치민시',
'lib.c25.eyb':'KSAPS 학술대회',
'lib.c25.loc':'하노이',
'lib.c25.venue':'108 중앙군사병원',
'lib.empty.title':'사진 준비 중',
'lib.empty.desc':'행사 사진은 행사 종료 후 업로드됩니다. 곧 하이라이트와 추억을 확인해 주세요.',
'lib.cta.eyb':'K-BEAUTY MEETS 2026',
'lib.cta.title':'<em>다음 장</em>의 주인공이 되세요',
'lib.cta.sub':'K-Beauty MEETS 2026에 지금 등록하세요 — 의료 전문가 무료.',
"Moments from":"순간들 —",
"Photos coming soon":"사진 준비 중",
"Event photos will be uploaded here after the event. Check back soon for highlights and memories.":"행사 사진은 행사 종료 후 업로드됩니다. 곧 하이라이트와 추억을 확인해 주세요.",
"Be part of the next chapter":"다음 장의 주인공이 되세요",
"Register now for K-Beauty MEETS 2026 — free for all medical professionals.":"K-Beauty MEETS 2026에 지금 등록하세요 — 의료 전문가 무료.",
"All Events":"전체",
"Library":"라이브러리"
};
